In [61]:
pathTextFileFeb='/Users/jatinanand/InterViewAssignments/TableTenisEvaluationApp/3monthsData/Rating/TextFiles/RatingsMarch(foxit.com).txt'
pathTextFileJan='/Users/jatinanand/InterViewAssignments/TableTenisEvaluationApp/3monthsData/Rating/TextFiles/Ratings-ListFeburary.txt'
pathTextFileDec='/Users/jatinanand/InterViewAssignments/TableTenisEvaluationApp/3monthsData/Rating/TextFiles/Rating-listJan.txt'

In [627]:
# D = open(pathTextFileDec)
# D = open(pathTextFileFeb)
D = open(pathTextFileJan)

In [628]:
RowText = D.read()

In [629]:
RowText

'Rating List\nPeriod: 18/6\nDate Range: (01/01/2019 to 31/01/2019)\nVersion: 5\nCategories\nCadet Boys (1222)\nCadet Girls (225)\nJunior Boys (1284)\nJunior Girls (221)\nSenior Men (1609)\nSenior Women (331)\nUnder 13 Boys (517)\nUnder 13 Girls (96)\nUnder 21 Men (487)\nUnder 21 Women (146)\nVeteran Men (1047)\nVeteran Women (210)\nForeign Players\nTournaments in this period\nBoston\\Winter 2018-19\n27/01/2019 - Ipswich Britannia Senior Super Series\n27/01/2019 - Hunts 2*-Juniors\n27/01/2019 - Hunts 2*-Cadets\n27/01/2019 - NJL-3-Plymouth\n27/01/2019 - NCL-3-Woodgreen\n27/01/2019 - NJL-3-Bristol\nBritishLeague\\Womens 2018-2019\n26/01/2019 - NJL-3-Tunbridge Wells\n26/01/2019 - NJL-3-Ormesby\n26/01/2019 - NJL-3-Woodgreen\n26/01/2019 - NJL-3-Cippenham\n26/01/2019 - NJL-2-Brighton\n26/01/2019 - NJL-3-Westfield\n26/01/2019 - NCL-2-Brighton\n26/01/2019 - NJL-3-Nottingham\n26/01/2019 - NJL-3-Waterside\n19/01/2019 - PG Mutual Senior National Championships Qualifer\n20/01/2019 - Bromley 2*-Senior\n20/01/2019 - County Championships- O60\'S\n19/01/2019 - County Championship Veterans Premier\n19/01/2019 - County Championships - Veterans\n07/10/2017 - County Championships - Veterans\n15/01/2019 - Hungarian Open Men\'s & Women\'s Singles\n12/01/2019 - Bath Grand Prix\n13/01/2019 - Bath Grand Prix - Veterans\n13/01/2019 - NCL-3-Morpeth\n12/01/2019 - NJL-3-Stowmarket\n12/01/2019 - NCL-3-Stowmarket\n13/01/2019 - NCL-3-Cirencester\n13/01/2019 - NCL-3-Ellenborough\n13/01/2019 - NJL-2-Sheffield\n13/01/2019 - NCL-3-Sheffield\n13/01/2019 - NCL-3-Waterside\n13/01/2019 - NCL-3-Cippenham\n13/01/2019 - NCL-3-Westfield\n13/01/2019 - NCL-3-Halton\n13/01/2019 - NCL-3-Greenhouse\n13/01/2019 - NCL-3-Garstang\n13/01/2019 - NJL-3-Garstang\nBritishLeague\\Premier 2018-19\n12/01/2019 - Corby Smash Veterans 1 *-Veterans\n09/01/2019 - Archway Peterborough Mid Week Medal 1*- Senior\n05/01/2019 - East Midlands Junior 4*-Cadet\n05/01/2019 - Vetts Southern Masters 040\'s Mens and Womens Singles\n06/01/2019 - Cippenham Team 2* Senior\n05/01/2019 - East Midlands Junior 4*-Junior\n05/01/2019 - County Championships - Senior\n02/01/2019 - County Championships - Veterans\nAll tournaments played this season can be viewed at the bottom of this report.\nNotes\nPlayers in this booklet are eligible to play in England but are not necessarily eligible to represent England in International Competition.\nIf no nationality is specified on your Table Tennis England membership profile, your country will appear as "-" and you will be listed as a Foreign Player.If no county of affiliation is specified on your Table Tennis England membership profile, your county will appear as “-“.\nSandra Pelizzoni\nTable Tennis England\nBradwell Road\nLoughton Lodge\nEmail: ranking@tabletennisengland.co.uk\nMK8 9LA\nEmail: sandra.pelizzoni@tabletennisengland.co.uk\nImportant Notice\nForeign players are dummies calculated from the top 30% of the ITTF World List. If a foreign player does not appear within this criteria their dummy rating will be entered as zero\napart from those players that regularly play in English tournaments.\nTable Tennis England accepts no responsibility of any kind for such errors and their consequences. Any mistake will be investigated and proven errors will be rectified in a\nsubsequent list. Any queries from the list should arrive within three weeks of the list publication date and be sent to:-\nYou can update your nationality and county of affiliation by logging into the Table Tennis England members area.Under 13 Girls\nPrev Pos Name County/Country Points Inactive Periods\n-1 1 Anna Hursey (6482) Wales 1153\n-2 2 Anna Green (156731) Nottinghamshire 918\n-3 3 Sophie Barcsai (183502) Dorset 771 1\n-4 4 Jyothirmayi Vaishnavi Ghanta (191086) Berkshire 764\n-5 5 Isabelle Lacorte (182285) Hertfordshire 684 1\n-6 6 Maliha Baig (182658) Essex 678 1\n-7 7 Saskia Key (175113) Kent 673\n-8 8 Bethany Ellis (176155) Lancashire 637\n-14 9 Connie Dumelow (190110) Derbyshire 636\n-12 10 Ruby Elliott (184582) Wales 576\n-9 11 Katie Bates (178432) ClevelandTTA 567\n(-) 12 Emily Flynn (201799) Ireland 564\n-11 13 Hannah Silcock (197105) Jersey 563\n-10 14 Kate Watkinson (184531) Lancashire 528\n-13 15 Sophie Richardson (189496) Durham 495 1\n-15 16 Sienna Jetha (189584) Middlesex 495\n-16 17 Jessica Moggeridge (182117) Dorset 484\n-19 18 Evelyn Pace (198287) Surrey 439\n-17 19 Anna Piercey (190241) Buckinghamshire 400\n-18 20 Rachael Iles (196802) Buckinghamshire 389\n-20 21 Inara Ahmed (188629) Derbyshire 314\n-25 22 Emily Cheung (190246) Surrey 299\n-21 23 Milly Hanrahan (189394) Cheshire 295\n-23 24 Chloe Kay (180047) Devonshire 292 1\n-24 25 Jessica Morris (196044) Cheshire 292\n-22 26 Darcy Brewer (177360) Norfolk 285\n-26 27 Maddy Lyons (190218) Cheshire 239\n-27 28 Sophie Ackred (192275) Cumbria-TableTennisEngland 238\n-28 29 Sasha Lewis (191022) Wales 235\n-33 30 Jessica Felton (174473) Lancashire 230\n-29 31 Mia Longman (190860) Yorkshire 226 2\n-48 32 Chui-Que Wong (198386) - 215\n-30 33 Lucy Bridle (178266) Lincolnshire 210 1\n-34 34 Shaniely Edwards (191936) Bedfordshire 207\n-31 35 Mabel Shute (196700) Essex 205\n-49 36 Ashleigh Browne (196457) Dorset 203\n-35 37 Naomi Coker (193965) Derbyshire 193\n-41 38 Inderjeet Pawar (191091) - 191\n-54 39 Katie Le Peuple (197919) Hampshire 191\n-38 40 Anna Walsh (185425) Lancashire 190\n-39 41 Lilly Atkin (200469) Buckinghamshire 184\n-37 42 Bella Tonev (196386) Buckinghamshire 183\n-42 43 Anna Hartley (189397) Cheshire 181\n-32 44 Caron Charles (193390) Surrey 173\n-44 45 Evie Davies (177799) - 168\n-36 46 Calina Dawson (193394) India 161\n-40 47 Gypsie Kay (180048) Devonshire 159 1\n(-) 48 Georgina Hunter (200992) Sussex 155\n(-) 49 Maddie Edwards (200812) - 152 1\n-43 50 Roma Morjaria (188774) Leicestershire 144 2\n-58 51 Amirah Ali Amirah (196255) - 135\n-46 52 Niranjana Perumal (198096) - 130 3\n-55 53 Bethany Pye (199463) Worcestershire 130\n-45 54 Aliya Power (200471) Buckinghamshire 126\n-57 55 Jonabel Taguibao (201472) - 124 1\n-53 56 Marlie Gregory (191459) Buckinghamshire 121\n-51 57 Seren Jones (197250) Wales 120\n-47 58 Vibha Mali (191426) Berkshire 119\n-56 59 Ella Pashley (200336) ClevelandTTA 119\n(-) 60 Francis Haber (200824) - 116 1\n-60 61 Emily Koester (190228) - 115\n-65 62 Luna Archard (201471) - 115\n(-) 63 Ella Weavers (194934) - 110 1\n-50 64 Jessica Millington (197799) - 109\n-52 65 Phoebe Tomlinson (190113) Nottinghamshire 108\n-66 66 Eva Eccles (190608) Norfolk 106\n-75 67 Sally Atkinson (195111) - 104 1\n-59 68 Marissa Brooks (194445) Norfolk 101 2\n-61 69 Emily Roberts (196482) - 98 1\n-62 70 Isabella Reid (199818) Worcestershire 98 1\n-63 71 Olivia Miners (200043) - 96 1\n-64 72 Anika Bansal (190527) Yorkshire 93 1\n(-) 73 Gabriella Cooke (200813) - 91 1\n-69 74 Orlaith Burgess (190148) Suffolk 79\n-70 75 Evie Ferrar (195084) - 76 1\n-67 76 Elise Davies (195652) - 65\n-68 77 Holly Swarbrick (199250) - 62\n-71 78 Rachel Lane (195484) Cheshire 59 1\n-73 79 Freya Wynne (186314) - 39 1\n-76 80 Brooke Morris (188654) - 38-74 81 Miri Rosenberg (198583) - 38 3\n-72 82 Scarlett McDonagh (184308) - 33\n-77 83 Phoenix Mason (192335) Lincolnshire 16 1\n-78 84 Hallie Tallentire (189696) - 10 4Under 13 Boys\nPrev Pos Name County/Country Points Inactive Periods\n-1 1 Connor Green (156730) Nottinghamshire 1289\n-3 2 Jakub Piwowar (169093) Devonshire 1140\n-2 3 Oliver Maric - Murray (174742) Surrey 1132 1\n-4 4 Joseph Hunter (190005) Middlesex 1113 1\n-5 5 James Hamblett (176178) Hertfordshire 1019\n-6 6 Harry Yip (166327) Sussex 998\n-7 7 Nathaniel Saunders (179165) Warwickshire 868\n-9 8 Jake Haygarth (182541) Durham 830\n-8 9 Georgios Gerakios (179013) Nottinghamshire 826\n-10 10 Adam Dennison (184286) Lancashire 813\n-11 11 Thomas Palmer (176045) Middlesex 778\n-12 12 Joseph Cooper (177410) Derbyshire 762\n-13 13 Ben Poulter (182247) Hampshire 746\n-14 14 Tom Powlesland (175943) Gloucestershire 721\n-15 15 Lennon Maughan (185573) Yorkshire 719 2\n-20 16 Joseph Dennison (184287) Lancashire 713\n-16 17 Jenson Moreno (184114) Middlesex 687 1\n-21 18 Ethan Eaketts (182766) Hertfordshire 660 1\n-18 19 Luke Hodgson (170827) Yorkshire 642 2\n-19 20 Charlie Nabarro (180148) Middlesex 641 1\n-17 21 Francesco Bonato (182073) Surrey 638 1\n-30 22 Rhys Hetherton (197248) Wales 636\n-25 23 Cameron Driver (179075) Nottinghamshire 615\n-29 24 Louis Cheung Turner (186488) Lancashire 607 1\n-35 25 George Noel (191117) Surrey 606\n-22 26 Luke Lowther (189829) Yorkshire 603 2\n-23 27 Jake Hewitt (183821) Yorkshire 598 2\n-24 28 Ojasvii Borah (192362) Surrey 598\n-26 29 Ralph Pattison (190460) Essex 595\n-27 30 Adam Palmer (193430) Surrey 573\n-28 31 Gene McGhee (176103) ClevelandTTA 554 3\n-66 32 Daniel Jones (189652) Staffordshire 550\n-33 33 Jacob Archer (191178) Surrey 538\n-36 34 Henry Shaw (169650) Suffolk 531\n-32 35 Larry Trumpauskas (176501) Kent 530 2\n-40 36 Daniel Clark (190852) Surrey 526\n-31 37 Thomas Nicol (177500) Bedfordshire 525\n-34 38 Mark Balon (177396) Cambridgeshire 515\n-39 39 Krish Chotai (180127) Surrey 514\n-42 40 Sam Gabriel (185981) Middlesex 510\n-41 41 Abraham Earl Sellado (185015) Yorkshire 496\n-47 42 Kamari Jagdeo-Bailey (172300) Essex 490\n-45 43 Eduard Lakatos (172957) Berkshire 490\n-38 44 Ibrahim Abdullah (190885) Cheshire 485 2\n-37 45 Siva Pranav Ghanta (191087) Berkshire 482\n-48 46 James Millward (182620) Nottinghamshire 473\n-44 47 Max Wilson (182282) Sussex 469\n-43 48 Ben Mold (184706) Durham 456\n-72 49 Christopher Ho (192327) Warwickshire 455\n-57 50 Yiannis Kazantzidis (196489) - 444\n-46 51 Ben Porter (189516) - 443\n-59 52 Benjamin Dunkley (188110) Bedfordshire 436\n-51 53 Frederick Jones (179064) Nottinghamshire 434\n-82 54 Chidumebi Egbeama (196462) Surrey 426\n-85 55 Evan Williams (197249) Wales 425\n-52 56 Henri Montana (179065) Nottinghamshire 409\n-54 57 James Donald (193857) Essex 398\n-53 58 George Jackson (190519) - 391\n-67 59 Noah Van Hoorebeek (192012) - 391\n-49 60 Louis Vaughn Drake (194796) - 389\n-56 61 Joel Smith (192689) Lincolnshire 388\n-60 62 Bailey Page (189537) Devonshire 385\n-50 63 Charlie Dolton (182075) Devonshire 378\n-58 64 Tobias Fletcher (180030) - 373\n-64 65 Aarav Shah (188393) Middlesex 369\n-65 66 Daniyal Palmer (193449) Surrey 360\n-61 67 Daniel Goitom (196095) - 359\n-63 68 Ben Aldridge (170936) Northamptonshire 355\n-55 69 William Saint (190401) - 355\n-71 70 Lucas Gabb (193247) Surrey 355\n-84 71 Shantosh Thevarasa (199541) Surrey 353\n-104 72 Louis Treffel (187652) - 347\n-62 73 Sam Taylor (187002) Essex 346\n-68 74 Sam Davies (183118) Cheshire 343\n-74 75 Alessandro Mitranescu (195508) Devonshire 338\n-83 76 Joseph Fortnum-Adams (190721) Suffolk 333\n-81 77 Matthew Davies (188143) Kent 328\n-70 78 Hugo Nguyen (187500) Devonshire 323 1\n-69 79 Max Radiven (188645) Middlesex 320 1\n-78 80 Kai Sun Yiu (193650) Surrey 309-89 81 Isaac Kingham (190072) Suffolk 307\n-79 82 Jack Smith (184273) Hampshire 304\n-75 83 Ptolemy Beman (168019) Devonshire 299\n-90 84 Charlie Davidson (177932) Gloucestershire 298\n-76 85 Tommy Lyons (182046) - 298 1\n-77 86 Jonah Hannaway (177525) ClevelandTTA 295 1\n-80 87 Leo Nguyen (187501) Devonshire 290 1\n-73 88 Connor Hallford (186145) SouthYorkshire 289\n-100 89 Jared Hon (197255) Hampshire 289\n-86 90 Toby Zeffie (184463) Essex 281\n-96 91 Cyrus Harris (192907) Warwickshire 281\n-106 92 Noah Hacking (189613) - 278\n-101 93 Sam Piesley (183449) - 276\n-87 94 Louis Menzel (187772) - 276 1\n-88 95 Riley Astle (186564) SouthYorkshire 275 1\n-102 96 Harrison Cunningham (194506) - 267\n-91 97 Benjamin Levi (197542) - 266 3\n-154 98 Jack Palfrey (197696) Wales 263\n-94 99 Jake Crane (180390) - 260 1\n-93 100 Logan Macey (189433) Dorset 260\n(-) 101 Zack Bull (199450) Sussex 253\n-98 102 George Barnes (189346) - 250\n-95 103 Thomas Henrici (201604) United States of America 249 1\n-92 104 Jamie Woodford (198814) - 246\n-107 105 Henry James (192550) Derbyshire 243\n-105 106 Justin Fisher (198449) Hertfordshire 242\n-131 107 Reuben Yates (188489) - 240\n-129 108 Dominic Evans (190144) Shropshire 231\n-109 109 Joseph Buscombe (190446) - 229\n-121 110 Kamil Tanaka (198091) Poland 229\n-124 111 Reuben Orange (183052) - 227\n-143 112 Guy Attew (189377) Suffolk 224\n-130 113 Leon Cain (194793) Sussex 220\n-114 114 Jheng Lee (198862) - 220\n(-) 115 Charlie Alder (199606) - 220 1\n-122 116 George Goodwin (190233) - 218 1\n-116 117 Connor Austin (190717) Sussex 218\n-126 118 Luke Hyde (187857) Lincolnshire 217\n-103 119 Elliot Miller (194325) Buckinghamshire 217\n-108 120 Zack Wood (197658) - 217 2\n-113 121 Liam Cyzman (191396) Poland 216 1\n-139 122 James Hobbs (187237) Lincolnshire 215 1\n-99 123 Henry Clarke (197599) Worcestershire 215\n-236 124 Lewis Austin (190716) Sussex 214\n-111 125 Alexander Wardrop (191510) - 214 1\n-117 126 Gosinachid Egbeama (201003) Surrey 213\n-115 127 Rishan Ganatra (162824) Northamptonshire 211 2\n-133 128 Elliott Knott (197143) - 211\n-112 129 Charlie Drabble (187586) Somerset 209\n-229 130 Stanley Barclay (194576) - 207\n(-) 131 Rees Christina (201206) - 205 1\n-118 132 Nathan Theakston (171397) Durham 204 2\n-123 133 Oliver Tozer (196967) - 204\n-162 134 Thomas Agombar (198649) Hampshire 204\n-119 135 Jack Savage (178596) Lancashire 203 2\n-110 136 Alejandro Montero Vasquez (187951) Spain 203\n-132 137 Toby Harwood (191020) Wales 202\n-120 138 Oliver Barton (192847) - 202\n-127 139 Toby McLoughlin (199197) - 200\n-168 140 Gus Leggat (200912) - 200\n(-) 141 Jude Lane (199555) - 199\n-152 142 Toby Marshall (179542) Somerset 198\n-150 143 Kristof Polgar (200237) Hungary 198\n-219 144 Zakir Zephyr (200539) - 198\n(-) 145 Edward Eddery (187116) - 196\n-125 146 Rudii Richards (179170) - 195 2\n-141 147 Harrison Creak (189612) - 195\n(-) 148 Owen Davies (199673) Sussex 195\n-159 149 Joseph Fisher (191535) Oxfordshire 194\n(-) 150 Adam Gold (189784) - 193 2\n-147 151 Anand Raviprakash (175641) Durham 191\n-188 152 Matthew Stewart (194266) Yorkshire 191\n-199 153 Kwame Sousseing (195033) - 190\n-172 154 Edward Overy (196718) Buckinghamshire 190\n-145 155 Adam Anderson (171168) Worcestershire 188\n-144 156 Kacper Piwowar (179698) Devonshire 188 1\n-198 157 Felix Jones (196488) - 187\n-135 158 Joey Page (190445) - 185\n-142 159 Aditya Mali (191425) Berkshire 185\n(-) 160 Samuel Darley (201402) - 185 1\n-166 161 Felix West (185886) Dorset 184\n-158 162 Firas Fakhera (200632) - 184-251 163 Rahil Rehman-Furs (195501) Sussex 181\n(-) 164 Harry Llewellyn (200706) - 181\n-138 165 Samuel Melhuish (184143) Dorset 179 1\n-175 166 James Stein (192914) - 179\n-140 167 Ty Dennis-Thompson (197704) Kent 179 4\n-177 168 Tom Meredith (192489) - 178\n(-) 169 Aryan Sharma (200703) Essex 178\n-215 170 Ben Hawes (195537) - 177\n-196 171 George Driscoll (201020) - 177\n-163 172 Jack Cooper (195329) - 176\n-128 173 Abiram Nagarajan (191171) - 175\n(-) 174 Akilesh Reetoo (200536) - 175\n-137 175 Kushagra Verma (176656) Surrey 174 1\n-148 176 Ryan Tailor (182697) Middlesex 174 4\n-156 177 Jun Chung (195891) - 174\n-149 178 Zac Greenhough (198596) - 174 2\n-151 179 Seth Holland (192313) ClevelandTTA 173 1\n(-) 180 George Baxter (201043) - 173\n-161 181 Reece Oliver (201056) - 172\n-180 182 Samuel Arnott (188752) Kent 169\n-146 183 Senura Perera (201051) Buckinghamshire 169\n-250 184 Ryan Camelo (193167) Wiltshire 168\n-183 185 Nyle Campbell (201467) - 168\n-153 186 Mikul Patel (194279) Staffordshire 167\n(-) 187 Sudheep Kamma (179233) Essex 164\n-197 188 Jamie Anderson (164379) Northamptonshire 163\n-185 189 Brennan Foster (198097) Lancashire 163\n-165 190 Wajid Wafiq (184606) Warwickshire 161\n-234 191 Shishir Shastry (192608) - 161\n(-) 192 Michael Downey (194313) Cheshire 161\n-171 193 Zach Youngs (200205) - 161\n(-) 194 James Brandon (199226) - 160\n(-) 195 Jake Shepherd (179973) - 159\n-202 196 Noah Unstead (190064) - 159\n(-) 197 Benji Moore (201107) - 159 1\n-184 198 Morgan Barrell (174639) Nottinghamshire 158\n-193 199 Charlie Williams (194646) Lancashire 158\n-155 200 Daniel Heap (187012) SouthYorkshire 157\n-201 201 Azaan Ali (195980) Berkshire 156\n-267 202 Felipe Fujimori (194651) Kent 155\n-136 203 Henry Harding (195616) Buckinghamshire 155\n-167 204 Thanh Nguyen (195460) - 154 4\n-164 205 Christopher Chin (197150) Kent 154\n-210 206 Harrison Taylor (198798) - 153 1\n-261 207 Harry Whiteley (197164) - 152\n(-) 208 Adrian Randis (198706) Czech Republic 152\n(-) 209 Oliver Dugaric (184085) Middlesex 151 2\n(-) 210 Micah Smith (201271) - 151 1\n(-) 211 Sam Mockett (199062) - 150\n-190 212 Oliver Ferguson (186436) Warwickshire 149\n(-) 213 Ben Grifiths (200612) - 149\n-170 214 Prateek Sai Divakarla (197615) - 148 2\n-247 215 Evan Perkins (198136) - 147\n(-) 216 Alfie Lockwood (199535) - 147\n-179 217 George McAdam (184994) Durham 146\n-157 218 Seth Mayuga (190131) - 146\n(-) 219 Evan Erskine (198929) Sussex 146\n(-) 220 Logan Newton (199388) - 146\n-222 221 Josh White (199536) Dorset 146\n-248 222 Ethan Lynn (180748) SouthYorkshire 145\n-192 223 Archie Fyfe (192843) Oxfordshire 145\n(-) 224 Stephen Ledger (199412) Sussex 145\n-169 225 Daniel Stone (187593) Warwickshire 144\n-225 226 Owain Osmond Gillam (187709) Surrey 144\n-176 227 Louis Fell (199472) Yorkshire 143 1\n-134 228 Elis O\'Connor (184117) Wales 142\n(-) 229 Adam Cort (196244) Sussex 142\n-160 230 Ben Keeley (196699) Cheshire 142\n-246 231 Yusuf Zephyr (200537) - 142\n-173 232 Adam Staiger-Grant (189535) - 141 1\n(-) 233 Max Gonpot (190220) France 141\n-238 234 Seyaan Budkhar (195942) Berkshire 141\n-211 235 William Bevan (199323) - 141\n-269 236 William Hopkins (199766) - 141\n-260 237 Charlie Searle (194964) - 140\n(-) 238 Chris Coombe (201712) Sussex 140\n-181 239 Zoltan Koszo (192872) Hungary 139 1\n(-) 240 Alain Shibu (195276) India 139\n-206 241 Edward Heather (199886) Lincolnshire 138\n-182 242 Thomas Swarbrick (198937) - 137 1\n-207 243 James Titmas (185809) Berkshire 136\n-254 244 Konrad Johnson (188367) Kent 136-257 245 Finlay Vickers (200904) Lincolnshire 136 1\n-189 246 Jayden Sonnabend (197619) - 135 2\n(-) 247 George Reynolds (199928) - 135\n-216 248 Haryram Sri Rajakumar (200082) Germany 135\n-191 249 Ethan McAndrew (195969) - 134 2\n-233 250 Jack Jordan (188154) Kent 133\n-174 251 Morris Wong (190688) Oxfordshire 133\n-209 252 Ivan Vaplaks (195961) - 132 1\n-195 253 James Rissen (196727) - 131 2\n(-) 254 Raghav Chandra (201524) - 131\n-264 255 Alexander Gosling (171623) Suffolk 130\n-194 256 Timothy James (195389) ClevelandTTA 130\n(-) 257 Harvey Sandwell (202020) Sussex 130\n(-) 258 Pablo Ramirez Rioja (197856) Hertfordshire 129\n(-) 259 Joshua Pullen (199524) - 129\n(-) 260 Jason Bourne (200118) - 129\n(-) 261 Joseph Garrett-Kelly (191280) - 127\n-200 262 Joseph Edwards (195770) - 127 1\n(-) 263 Harry Chitty (201662) - 127\n-226 264 Fergus Brown (192699) Yorkshire 126 1\n-243 265 Amaan Umar (195798) Yorkshire 126\n-227 266 Zachary Barras (199650) Dorset 126\n-208 267 Alec Lyons (190848) - 125 1\n-304 268 Alexander Graham (196846) Suffolk 125\n(-) 269 Monty Mason (199547) - 125\n-298 270 Ben McKay (194856) Kent 122\n(-) 271 Ollie Nicholson (195108) - 122 1\n-232 272 Aarav Koteshwar (201050) Buckinghamshire 122\n-203 273 Mithran Patnaik (190256) Essex 121 1\n-235 274 Dylan Ufton (194173) Derbyshire 121\n(-) 275 Zaib Rehman-Furs (199444) - 121\n-217 276 George Fyfe (192864) Oxfordshire 120\n-283 277 Sonny Jordon (189418) Northamptonshire 119\n(-) 278 Adam Alibhai (196692) - 119\n-285 279 Harry Chivers (197348) - 119 2\n(-) 280 Rowan Smith (198938) - 119\n(-) 281 Timothy Mickler-Campbell (200718) - 119\n-186 282 Ollie Van Slooten (180305) Suffolk 117\n-244 283 Dominic Withers (187341) Nottinghamshire 117\n-178 284 Harry Randall (197083) Berkshire 117\n-281 285 Jake Davidson (177933) - 116\n-241 286 Thomas Hooks (178260) Warwickshire 116 2\n-221 287 Kieran O\'Callaghan (188379) Durham 116 1\n-237 288 Adam Akil (194245) - 116\n(-) 289 James Stanley (

In [630]:
NExtlineDataSplit=RowText.split('\n')

In [631]:
NExtlineDataSplit

['Rating List',
 'Period: 18/6',
 'Date Range: (01/01/2019 to 31/01/2019)',
 'Version: 5',
 'Categories',
 'Cadet Boys (1222)',
 'Cadet Girls (225)',
 'Junior Boys (1284)',
 'Junior Girls (221)',
 'Senior Men (1609)',
 'Senior Women (331)',
 'Under 13 Boys (517)',
 'Under 13 Girls (96)',
 'Under 21 Men (487)',
 'Under 21 Women (146)',
 'Veteran Men (1047)',
 'Veteran Women (210)',
 'Foreign Players',
 'Tournaments in this period',
 'Boston\\Winter 2018-19',
 '27/01/2019 - Ipswich Britannia Senior Super Series',
 '27/01/2019 - Hunts 2*-Juniors',
 '27/01/2019 - Hunts 2*-Cadets',
 '27/01/2019 - NJL-3-Plymouth',
 '27/01/2019 - NCL-3-Woodgreen',
 '27/01/2019 - NJL-3-Bristol',
 'BritishLeague\\Womens 2018-2019',
 '26/01/2019 - NJL-3-Tunbridge Wells',
 '26/01/2019 - NJL-3-Ormesby',
 '26/01/2019 - NJL-3-Woodgreen',
 '26/01/2019 - NJL-3-Cippenham',
 '26/01/2019 - NJL-2-Brighton',
 '26/01/2019 - NJL-3-Westfield',
 '26/01/2019 - NCL-2-Brighton',
 '26/01/2019 - NJL-3-Nottingham',
 '26/01/2019 - NJL-3-Waterside',
 '19/01/2019 - PG Mutual Senior National Championships Qualifer',
 '20/01/2019 - Bromley 2*-Senior',
 "20/01/2019 - County Championships- O60'S",
 '19/01/2019 - County Championship Veterans Premier',
 '19/01/2019 - County Championships - Veterans',
 '07/10/2017 - County Championships - Veterans',
 "15/01/2019 - Hungarian Open Men's & Women's Singles",
 '12/01/2019 - Bath Grand Prix',
 '13/01/2019 - Bath Grand Prix - Veterans',
 '13/01/2019 - NCL-3-Morpeth',
 '12/01/2019 - NJL-3-Stowmarket',
 '12/01/2019 - NCL-3-Stowmarket',
 '13/01/2019 - NCL-3-Cirencester',
 '13/01/2019 - NCL-3-Ellenborough',
 '13/01/2019 - NJL-2-Sheffield',
 '13/01/2019 - NCL-3-Sheffield',
 '13/01/2019 - NCL-3-Waterside',
 '13/01/2019 - NCL-3-Cippenham',
 '13/01/2019 - NCL-3-Westfield',
 '13/01/2019 - NCL-3-Halton',
 '13/01/2019 - NCL-3-Greenhouse',
 '13/01/2019 - NCL-3-Garstang',
 '13/01/2019 - NJL-3-Garstang',
 'BritishLeague\\Premier 2018-19',
 '12/01/2019 - Corby Smash Veterans 1 *-Veterans',
 '09/01/2019 - Archway Peterborough Mid Week Medal 1*- Senior',
 '05/01/2019 - East Midlands Junior 4*-Cadet',
 "05/01/2019 - Vetts Southern Masters 040's Mens and Womens Singles",
 '06/01/2019 - Cippenham Team 2* Senior',
 '05/01/2019 - East Midlands Junior 4*-Junior',
 '05/01/2019 - County Championships - Senior',
 '02/01/2019 - County Championships - Veterans',
 'All tournaments played this season can be viewed at the bottom of this report.',
 'Notes',
 'Players in this booklet are eligible to play in England but are not necessarily eligible to represent England in International Competition.',
 'If no nationality is specified on your Table Tennis England membership profile, your country will appear as "-" and you will be listed as a Foreign Player.If no county of affiliation is specified on your Table Tennis England membership profile, your county will appear as “-“.',
 'Sandra Pelizzoni',
 'Table Tennis England',
 'Bradwell Road',
 'Loughton Lodge',
 'Email: ranking@tabletennisengland.co.uk',
 'MK8 9LA',
 'Email: sandra.pelizzoni@tabletennisengland.co.uk',
 'Important Notice',
 'Foreign players are dummies calculated from the top 30% of the ITTF World List. If a foreign player does not appear within this criteria their dummy rating will be entered as zero',
 'apart from those players that regularly play in English tournaments.',
 'Table Tennis England accepts no responsibility of any kind for such errors and their consequences. Any mistake will be investigated and proven errors will be rectified in a',
 'subsequent list. Any queries from the list should arrive within three weeks of the list publication date and be sent to:-',
 'You can update your nationality and county of affiliation by logging into the Table Tennis England members area.Under 13 Girls',
 'Prev Pos Name County/Country Points Inactive Periods',
 '-1 1 Anna Hursey (6482) Wales 1153',
 '-2 2 Anna Green (156731) Nottinghamshire 918',
 '-3 3 Sophie Barcsai (183502) Dorset 771 1',
 '-4 4 Jyothirmayi Vaishnavi Ghanta (191086) Berkshire 764',
 '-5 5 Isabelle Lacorte (182285) Hertfordshire 684 1',
 '-6 6 Maliha Baig (182658) Essex 678 1',
 '-7 7 Saskia Key (175113) Kent 673',
 '-8 8 Bethany Ellis (176155) Lancashire 637',
 '-14 9 Connie Dumelow (190110) Derbyshire 636',
 '-12 10 Ruby Elliott (184582) Wales 576',
 '-9 11 Katie Bates (178432) ClevelandTTA 567',
 '(-) 12 Emily Flynn (201799) Ireland 564',
 '-11 13 Hannah Silcock (197105) Jersey 563',
 '-10 14 Kate Watkinson (184531) Lancashire 528',
 '-13 15 Sophie Richardson (189496) Durham 495 1',
 '-15 16 Sienna Jetha (189584) Middlesex 495',
 '-16 17 Jessica Moggeridge (182117) Dorset 484',
 '-19 18 Evelyn Pace (198287) Surrey 439',
 '-17 19 Anna Piercey (190241) Buckinghamshire 400',
 '-18 20 Rachael Iles (196802) Buckinghamshire 389',
 '-20 21 Inara Ahmed (188629) Derbyshire 314',
 '-25 22 Emily Cheung (190246) Surrey 299',
 '-21 23 Milly Hanrahan (189394) Cheshire 295',
 '-23 24 Chloe Kay (180047) Devonshire 292 1',
 '-24 25 Jessica Morris (196044) Cheshire 292',
 '-22 26 Darcy Brewer (177360) Norfolk 285',
 '-26 27 Maddy Lyons (190218) Cheshire 239',
 '-27 28 Sophie Ackred (192275) Cumbria-TableTennisEngland 238',
 '-28 29 Sasha Lewis (191022) Wales 235',
 '-33 30 Jessica Felton (174473) Lancashire 230',
 '-29 31 Mia Longman (190860) Yorkshire 226 2',
 '-48 32 Chui-Que Wong (198386) - 215',
 '-30 33 Lucy Bridle (178266) Lincolnshire 210 1',
 '-34 34 Shaniely Edwards (191936) Bedfordshire 207',
 '-31 35 Mabel Shute (196700) Essex 205',
 '-49 36 Ashleigh Browne (196457) Dorset 203',
 '-35 37 Naomi Coker (193965) Derbyshire 193',
 '-41 38 Inderjeet Pawar (191091) - 191',
 '-54 39 Katie Le Peuple (197919) Hampshire 191',
 '-38 40 Anna Walsh (185425) Lancashire 190',
 '-39 41 Lilly Atkin (200469) Buckinghamshire 184',
 '-37 42 Bella Tonev (196386) Buckinghamshire 183',
 '-42 43 Anna Hartley (189397) Cheshire 181',
 '-32 44 Caron Charles (193390) Surrey 173',
 '-44 45 Evie Davies (177799) - 168',
 '-36 46 Calina Dawson (193394) India 161',
 '-40 47 Gypsie Kay (180048) Devonshire 159 1',
 '(-) 48 Georgina Hunter (200992) Sussex 155',
 '(-) 49 Maddie Edwards (200812) - 152 1',
 '-43 50 Roma Morjaria (188774) Leicestershire 144 2',
 '-58 51 Amirah Ali Amirah (196255) - 135',
 '-46 52 Niranjana Perumal (198096) - 130 3',
 '-55 53 Bethany Pye (199463) Worcestershire 130',
 '-45 54 Aliya Power (200471) Buckinghamshire 126',
 '-57 55 Jonabel Taguibao (201472) - 124 1',
 '-53 56 Marlie Gregory (191459) Buckinghamshire 121',
 '-51 57 Seren Jones (197250) Wales 120',
 '-47 58 Vibha Mali (191426) Berkshire 119',
 '-56 59 Ella Pashley (200336) ClevelandTTA 119',
 '(-) 60 Francis Haber (200824) - 116 1',
 '-60 61 Emily Koester (190228) - 115',
 '-65 62 Luna Archard (201471) - 115',
 '(-) 63 Ella Weavers (194934) - 110 1',
 '-50 64 Jessica Millington (197799) - 109',
 '-52 65 Phoebe Tomlinson (190113) Nottinghamshire 108',
 '-66 66 Eva Eccles (190608) Norfolk 106',
 '-75 67 Sally Atkinson (195111) - 104 1',
 '-59 68 Marissa Brooks (194445) Norfolk 101 2',
 '-61 69 Emily Roberts (196482) - 98 1',
 '-62 70 Isabella Reid (199818) Worcestershire 98 1',
 '-63 71 Olivia Miners (200043) - 96 1',
 '-64 72 Anika Bansal (190527) Yorkshire 93 1',
 '(-) 73 Gabriella Cooke (200813) - 91 1',
 '-69 74 Orlaith Burgess (190148) Suffolk 79',
 '-70 75 Evie Ferrar (195084) - 76 1',
 '-67 76 Elise Davies (195652) - 65',
 '-68 77 Holly Swarbrick (199250) - 62',
 '-71 78 Rachel Lane (195484) Cheshire 59 1',
 '-73 79 Freya Wynne (186314) - 39 1',
 '-76 80 Brooke Morris (188654) - 38-74 81 Miri Rosenberg (198583) - 38 3',
 '-72 82 Scarlett McDonagh (184308) - 33',
 '-77 83 Phoenix Mason (192335) Lincolnshire 16 1',
 '-78 84 Hallie Tallentire (189696) - 10 4Under 13 Boys',
 'Prev Pos Name County/Country Points Inactive Periods',
 '-1 1 Connor Green (156730) Nottinghamshire 1289',
 '-3 2 Jakub Piwowar (169093) Devonshire 1140',
 '-2 3 Oliver Maric - Murray (174742) Surrey 1132 1',
 '-4 4 Joseph Hunter (190005) Middlesex 1113 1',
 '-5 5 James Hamblett (176178) Hertfordshire 1019',
 '-6 6 Harry Yip (166327) Sussex 998',
 '-7 7 Nathaniel Saunders (179165) Warwickshire 868',
 '-9 8 Jake Haygarth (182541) Durham 830',
 '-8 9 Georgios Gerakios (179013) Nottinghamshire 826',
 '-10 10 Adam Dennison (184286) Lancashire 813',
 '-11 11 Thomas Palmer (176045) Middlesex 778',
 '-12 12 Joseph Cooper (177410) Derbyshire 762',
 '-13 13 Ben Poulter (182247) Hampshire 746',
 '-14 14 Tom Powlesland (175943) Gloucestershire 721',
 '-15 15 Lennon Maughan (185573) Yorkshire 719 2',
 '-20 16 Joseph Dennison (184287) Lancashire 713',
 '-16 17 Jenson Moreno (184114) Middlesex 687 1',
 '-21 18 Ethan Eaketts (182766) Hertfordshire 660 1',
 '-18 19 Luke Hodgson (170827) Yorkshire 642 2',
 '-19 20 Charlie Nabarro (180148) Middlesex 641 1',
 '-17 21 Francesco Bonato (182073) Surrey 638 1',
 '-30 22 Rhys Hetherton (197248) Wales 636',
 '-25 23 Cameron Driver (179075) Nottinghamshire 615',
 '-29 24 Louis Cheung Turner (186488) Lancashire 607 1',
 '-35 25 George Noel (191117) Surrey 606',
 '-22 26 Luke Lowther (189829) Yorkshire 603 2',
 '-23 27 Jake Hewitt (183821) Yorkshire 598 2',
 '-24 28 Ojasvii Borah (192362) Surrey 598',
 '-26 29 Ralph Pattison (190460) Essex 595',
 '-27 30 Adam Palmer (193430) Surrey 573',
 '-28 31 Gene McGhee (176103) ClevelandTTA 554 3',
 '-66 32 Daniel Jones (189652) Staffordshire 550',
 '-33 33 Jacob Archer (191178) Surrey 538',
 '-36 34 Henry Shaw (169650) Suffolk 531',
 '-32 35 Larry Trumpauskas (176501) Kent 530 2',
 '-40 36 Daniel Clark (190852) Surrey 526',
 '-31 37 Thomas Nicol (177500) Bedfordshire 525',
 '-34 38 Mark Balon (177396) Cambridgeshire 515',
 '-39 39 Krish Chotai (180127) Surrey 514',
 '-42 40 Sam Gabriel (185981) Middlesex 510',
 '-41 41 Abraham Earl Sellado (185015) Yorkshire 496',
 '-47 42 Kamari Jagdeo-Bailey (172300) Essex 490',
 '-45 43 Eduard Lakatos (172957) Berkshire 490',
 '-38 44 Ibrahim Abdullah (190885) Cheshire 485 2',
 '-37 45 Siva Pranav Ghanta (191087) Berkshire 482',
 '-48 46 James Millward (182620) Nottinghamshire 473',
 '-44 47 Max Wilson (182282) Sussex 469',
 '-43 48 Ben Mold (184706) Durham 456',
 '-72 49 Christopher Ho (192327) Warwickshire 455',
 '-57 50 Yiannis Kazantzidis (196489) - 444',
 '-46 51 Ben Porter (189516) - 443',
 '-59 52 Benjamin Dunkley (188110) Bedfordshire 436',
 '-51 53 Frederick Jones (179064) Nottinghamshire 434',
 '-82 54 Chidumebi Egbeama (196462) Surrey 426',
 '-85 55 Evan Williams (197249) Wales 425',
 '-52 56 Henri Montana (179065) Nottinghamshire 409',
 '-54 57 James Donald (193857) Essex 398',
 '-53 58 George Jackson (190519) - 391',
 '-67 59 Noah Van Hoorebeek (192012) - 391',
 '-49 60 Louis Vaughn Drake (194796) - 389',
 '-56 61 Joel Smith (192689) Lincolnshire 388',
 '-60 62 Bailey Page (189537) Devonshire 385',
 '-50 63 Charlie Dolton (182075) Devonshire 378',
 '-58 64 Tobias Fletcher (180030) - 373',
 '-64 65 Aarav Shah (188393) Middlesex 369',
 '-65 66 Daniyal Palmer (193449) Surrey 360',
 '-61 67 Daniel Goitom (196095) - 359',
 '-63 68 Ben Aldridge (170936) Northamptonshire 355',
 '-55 69 William Saint (190401) - 355',
 '-71 70 Lucas Gabb (193247) Surrey 355',
 '-84 71 Shantosh Thevarasa (199541) Surrey 353',
 '-104 72 Louis Treffel (187652) - 347',
 '-62 73 Sam Taylor (187002) Essex 346',
 '-68 74 Sam Davies (183118) Cheshire 343',
 '-74 75 Alessandro Mitranescu (195508) Devonshire 338',
 '-83 76 Joseph Fortnum-Adams (190721) Suffolk 333',
 '-81 77 Matthew Davies (188143) Kent 328',
 '-70 78 Hugo Nguyen (187500) Devonshire 323 1',
 '-69 79 Max Radiven (188645) Middlesex 320 1',
 '-78 80 Kai Sun Yiu (193650) Surrey 309-89 81 Isaac Kingham (190072) Suffolk 307',
 '-79 82 Jack Smith (184273) Hampshire 304',
 '-75 83 Ptolemy Beman (168019) Devonshire 299',
 '-90 84 Charlie Davidson (177932) Gloucestershire 298',
 '-76 85 Tommy Lyons (182046) - 298 1',
 '-77 86 Jonah Hannaway (177525) ClevelandTTA 295 1',
 '-80 87 Leo Nguyen (187501) Devonshire 290 1',
 '-73 88 Connor Hallford (186145) SouthYorkshire 289',
 '-100 89 Jared Hon (197255) Hampshire 289',
 '-86 90 Toby Zeffie (184463) Essex 281',
 '-96 91 Cyrus Harris (192907) Warwickshire 281',
 '-106 92 Noah Hacking (189613) - 278',
 '-101 93 Sam Piesley (183449) - 276',
 '-87 94 Louis Menzel (187772) - 276 1',
 '-88 95 Riley Astle (186564) SouthYorkshire 275 1',
 '-102 96 Harrison Cunningham (194506) - 267',
 '-91 97 Benjamin Levi (197542) - 266 3',
 '-154 98 Jack Palfrey (197696) Wales 263',
 '-94 99 Jake Crane (180390) - 260 1',
 '-93 100 Logan Macey (189433) Dorset 260',
 '(-) 101 Zack Bull (199450) Sussex 253',
 '-98 102 George Barnes (189346) - 250',
 '-95 103 Thomas Henrici (201604) United States of America 249 1',
 '-92 104 Jamie Woodford (198814) - 246',
 '-107 105 Henry James (192550) Derbyshire 243',
 '-105 106 Justin Fisher (198449) Hertfordshire 242',
 '-131 107 Reuben Yates (188489) - 240',
 '-129 108 Dominic Evans (190144) Shropshire 231',
 '-109 109 Joseph Buscombe (190446) - 229',
 '-121 110 Kamil Tanaka (198091) Poland 229',
 '-124 111 Reuben Orange (183052) - 227',
 '-143 112 Guy Attew (189377) Suffolk 224',
 '-130 113 Leon Cain (194793) Sussex 220',
 '-114 114 Jheng Lee (198862) - 220',
 '(-) 115 Charlie Alder (199606) - 220 1',
 '-122 116 George Goodwin (190233) - 218 1',
 '-116 117 Connor Austin (190717) Sussex 218',
 '-126 118 Luke Hyde (187857) Lincolnshire 217',
 '-103 119 Elliot Miller (194325) Buckinghamshire 217',
 '-108 120 Zack Wood (197658) - 217 2',
 '-113 121 Liam Cyzman (191396) Poland 216 1',
 '-139 122 James Hobbs (187237) Lincolnshire 215 1',
 '-99 123 Henry Clarke (197599) Worcestershire 215',
 '-236 124 Lewis Austin (190716) Sussex 214',
 '-111 125 Alexander Wardrop (191510) - 214 1',
 '-117 126 Gosinachid Egbeama (201003) Surrey 213',
 '-115 127 Rishan Ganatra (162824) Northamptonshire 211 2',
 '-133 128 Elliott Knott (197143) - 211',
 '-112 129 Charlie Drabble (187586) Somerset 209',
 '-229 130 Stanley Barclay (194576) - 207',
 '(-) 131 Rees Christina (201206) - 205 1',
 '-118 132 Nathan Theakston (171397) Durham 204 2',
 '-123 133 Oliver Tozer (196967) - 204',
 '-162 134 Thomas Agombar (198649) Hampshire 204',
 '-119 135 Jack Savage (178596) Lancashire 203 2',
 '-110 136 Alejandro Montero Vasquez (187951) Spain 203',
 '-132 137 Toby Harwood (191020) Wales 202',
 '-120 138 Oliver Barton (192847) - 202',
 '-127 139 Toby McLoughlin (199197) - 200',
 '-168 140 Gus Leggat (200912) - 200',
 '(-) 141 Jude Lane (199555) - 199',
 '-152 142 Toby Marshall (179542) Somerset 198',
 '-150 143 Kristof Polgar (200237) Hungary 198',
 '-219 144 Zakir Zephyr (200539) - 198',
 '(-) 145 Edward Eddery (187116) - 196',
 '-125 146 Rudii Richards (179170) - 195 2',
 '-141 147 Harrison Creak (189612) - 195',
 '(-) 148 Owen Davies (199673) Sussex 195',
 '-159 149 Joseph Fisher (191535) Oxfordshire 194',
 '(-) 150 Adam Gold (189784) - 193 2',
 '-147 151 Anand Raviprakash (175641) Durham 191',
 '-188 152 Matthew Stewart (194266) Yorkshire 191',
 '-199 153 Kwame Sousseing (195033) - 190',
 '-172 154 Edward Overy (196718) Buckinghamshire 190',
 '-145 155 Adam Anderson (171168) Worcestershire 188',
 '-144 156 Kacper Piwowar (179698) Devonshire 188 1',
 '-198 157 Felix Jones (196488) - 187',
 '-135 158 Joey Page (190445) - 185',
 '-142 159 Aditya Mali (191425) Berkshire 185',
 '(-) 160 Samuel Darley (201402) - 185 1',
 '-166 161 Felix West (185886) Dorset 184',
 '-158 162 Firas Fakhera (200632) - 184-251 163 Rahil Rehman-Furs (195501) Sussex 181',
 '(-) 164 Harry Llewellyn (200706) - 181',
 '-138 165 Samuel Melhuish (184143) Dorset 179 1',
 '-175 166 James Stein (192914) - 179',
 '-140 167 Ty Dennis-Thompson (197704) Kent 179 4',
 '-177 168 Tom Meredith (192489) - 178',
 '(-) 169 Aryan Sharma (200703) Essex 178',
 '-215 170 Ben Hawes (195537) - 177',
 '-196 171 George Driscoll (201020) - 177',
 '-163 172 Jack Cooper (195329) - 176',
 '-128 173 Abiram Nagarajan (191171) - 175',
 '(-) 174 Akilesh Reetoo (200536) - 175',
 '-137 175 Kushagra Verma (176656) Surrey 174 1',
 '-148 176 Ryan Tailor (182697) Middlesex 174 4',
 '-156 177 Jun Chung (195891) - 174',
 '-149 178 Zac Greenhough (198596) - 174 2',
 '-151 179 Seth Holland (192313) ClevelandTTA 173 1',
 '(-) 180 George Baxter (201043) - 173',
 '-161 181 Reece Oliver (201056) - 172',
 '-180 182 Samuel Arnott (188752) Kent 169',
 '-146 183 Senura Perera (201051) Buckinghamshire 169',
 '-250 184 Ryan Camelo (193167) Wiltshire 168',
 '-183 185 Nyle Campbell (201467) - 168',
 '-153 186 Mikul Patel (194279) Staffordshire 167',
 '(-) 187 Sudheep Kamma (179233) Essex 164',
 '-197 188 Jamie Anderson (164379) Northamptonshire 163',
 '-185 189 Brennan Foster (198097) Lancashire 163',
 '-165 190 Wajid Wafiq (184606) Warwickshire 161',
 '-234 191 Shishir Shastry (192608) - 161',
 '(-) 192 Michael Downey (194313) Cheshire 161',
 '-171 193 Zach Youngs (200205) - 161',
 '(-) 194 James Brandon (199226) - 160',
 '(-) 195 Jake Shepherd (179973) - 159',
 '-202 196 Noah Unstead (190064) - 159',
 '(-) 197 Benji Moore (201107) - 159 1',
 '-184 198 Morgan Barrell (174639) Nottinghamshire 158',
 '-193 199 Charlie Williams (194646) Lancashire 158',
 '-155 200 Daniel Heap (187012) SouthYorkshire 157',
 '-201 201 Azaan Ali (195980) Berkshire 156',
 '-267 202 Felipe Fujimori (194651) Kent 155',
 '-136 203 Henry Harding (195616) Buckinghamshire 155',
 '-167 204 Thanh Nguyen (195460) - 154 4',
 '-164 205 Christopher Chin (197150) Kent 154',
 '-210 206 Harrison Taylor (198798) - 153 1',
 '-261 207 Harry Whiteley (197164) - 152',
 '(-) 208 Adrian Randis (198706) Czech Republic 152',
 '(-) 209 Oliver Dugaric (184085) Middlesex 151 2',
 '(-) 210 Micah Smith (201271) - 151 1',
 '(-) 211 Sam Mockett (199062) - 150',
 '-190 212 Oliver Ferguson (186436) Warwickshire 149',
 '(-) 213 Ben Grifiths (200612) - 149',
 '-170 214 Prateek Sai Divakarla (197615) - 148 2',
 '-247 215 Evan Perkins (198136) - 147',
 '(-) 216 Alfie Lockwood (199535) - 147',
 '-179 217 George McAdam (184994) Durham 146',
 '-157 218 Seth Mayuga (190131) - 146',
 '(-) 219 Evan Erskine (198929) Sussex 146',
 '(-) 220 Logan Newton (199388) - 146',
 '-222 221 Josh White (199536) Dorset 146',
 '-248 222 Ethan Lynn (180748) SouthYorkshire 145',
 '-192 223 Archie Fyfe (192843) Oxfordshire 145',
 '(-) 224 Stephen Ledger (199412) Sussex 145',
 '-169 225 Daniel Stone (187593) Warwickshire 144',
 '-225 226 Owain Osmond Gillam (187709) Surrey 144',
 '-176 227 Louis Fell (199472) Yorkshire 143 1',
 "-134 228 Elis O'Connor (184117) Wales 142",
 '(-) 229 Adam Cort (196244) Sussex 142',
 '-160 230 Ben Keeley (196699) Cheshire 142',
 '-246 231 Yusuf Zephyr (200537) - 142',
 '-173 232 Adam Staiger-Grant (189535) - 141 1',
 '(-) 233 Max Gonpot (190220) France 141',
 '-238 234 Seyaan Budkhar (195942) Berkshire 141',
 '-211 235 William Bevan (199323) - 141',
 '-269 236 William Hopkins (199766) - 141',
 '-260 237 Charlie Searle (194964) - 140',
 '(-) 238 Chris Coombe (201712) Sussex 140',
 '-181 239 Zoltan Koszo (192872) Hungary 139 1',
 '(-) 240 Alain Shibu (195276) India 139',
 '-206 241 Edward Heather (199886) Lincolnshire 138',
 '-182 242 Thomas Swarbrick (198937) - 137 1',
 '-207 243 James Titmas (185809) Berkshire 136',
 '-254 244 Konrad Johnson (188367) Kent 136-257 245 Finlay Vickers (200904) Lincolnshire 136 1',
 '-189 246 Jayden Sonnabend (197619) - 135 2',
 '(-) 247 George Reynolds (199928) - 135',
 '-216 248 Haryram Sri Rajakumar (200082) Germany 135',
 '-191 249 Ethan McAndrew (195969) - 134 2',
 '-233 250 Jack Jordan (188154) Kent 133',
 '-174 251 Morris Wong (190688) Oxfordshire 133',
 '-209 252 Ivan Vaplaks (195961) - 132 1',
 '-195 253 James Rissen (196727) - 131 2',
 '(-) 254 Raghav Chandra (201524) - 131',
 '-264 255 Alexander Gosling (171623) Suffolk 130',
 '-194 256 Timothy James (195389) ClevelandTTA 130',
 '(-) 257 Harvey Sandwell (202020) Sussex 130',
 '(-) 258 Pablo Ramirez Rioja (197856) Hertfordshire 129',
 '(-) 259 Joshua Pullen (199524) - 129',

In [632]:
Start=0
End=0
for i in range(len(NExtlineDataSplit)):
    if(NExtlineDataSplit[i].find('Junior Girls')>-1):
        if(len(NExtlineDataSplit[i])>50):
            print(NExtlineDataSplit[i],len(NExtlineDataSplit[i]),i)
            Start=i
            break
for i in range(len(NExtlineDataSplit)):
    if(NExtlineDataSplit[i].find('Junior Boys')>-1):
        if(len(NExtlineDataSplit[i])>50):
            print(NExtlineDataSplit[i],len(NExtlineDataSplit[i]),i)
            End=i
            break

-795 921 Colney Vertigan (185354) Norfolk 10Junior Girls 56 1667
-169 170 Lucie Smith (167203) SouthYorkshire 13 2Junior Boys 60 1836

In [633]:
Start =Start+2

In [634]:
End=End+1

In [635]:
LforCrateInformationofPlayer=[]
while(Start<End):
    LforCrateInformationofPlayer.append(NExtlineDataSplit[Start])
#     print(NExtlineDataSplit[Start])
    Start += 1

In [636]:
LforCrateInformationofPlayer

['-2 1 Charlotte Bardsley (163059) Staffordshire 1488',
 '-1 2 Denise Payet (1344) Middlesex 1474 1',
 '-3 3 Jasmin Wong (165375) Yorkshire 1300',
 '-4 4 Mollie Patterson (446) Norfolk 1257',
 '-5 5 Darcie Proud (90566) Lincolnshire 1188',
 '-6 6 Anna Hursey (6482) Wales 1175',
 '-7 7 Annie Hedlund (198701) Sweden 1171 2',
 '-8 8 Megan Gidney (172935) Lancashire 1158',
 '-10 9 Beth Richards (170063) Wales 1106',
 '-9 10 Gauri Duhan (5655) Yorkshire 1070',
 '-16 11 Danielle Kelly (80573) Wales 1053',
 '-12 12 Ruby Chan (157565) Yorkshire 1033',
 '-14 13 Natalia Ianau (167173) Middlesex 1012',
 '-20 14 Mari Baldwin (175928) Devonshire 1012',
 '-11 15 Tiana Dennison (3289) Essex 1011',
 '-13 16 Gemma Kerr (165956) Devonshire 992',
 '-15 17 Anaya Patel (172772) Berkshire 991',
 '-21 18 Lara Whitton (166275) Wales 983',
 '-19 19 Katie Holt (3128) Dorset 980',
 '-17 20 Nomin Baasan (192519) Sweden 972 2',
 '-18 21 Millie Rogove (180435) Hertfordshire 970',
 '-23 22 Bhavika Mistry (8564) Northamptonshire 908',
 '-25 23 Lydia John (4765) Wales 884',
 '-22 24 Lois Perryman (281) Middlesex 883',
 '-24 25 Raquel São Pedro (186977) Lincolnshire 874',
 '-26 26 Sandy Choong (191450) Lancashire 861 1',
 '-28 27 Erin Green (156732) Nottinghamshire 852',
 '-27 28 Sophie Barlow (9039) ClevelandTTA 851 2',
 '-30 29 Grace Clement (176566) Wales 828',
 '-31 30 Charlotte Weatherby (2137) Durham 826',
 '(-) 31 Lauren Stacey (168508) Wales 814',
 '-29 32 Gracie Edwards (3426) Essex 799',
 '-36 33 Amy Marriott (172447) SouthYorkshire 789',
 '-41 34 Emily Haskell (7718) Devonshire 779',
 '-35 35 Kirsty Maull (170245) Staffordshire 773',
 '-32 36 Lucy Craig (170952) Northen Ireland 769',
 '-33 37 Federica Bonato (8007) Surrey 759',
 '-37 38 Jamie-Lee Harley (95252) Wales 754',
 "-45 39 Scarlett O'Neil (159169) Kent 753",
 '-34 40 Helena Dicken (165503) Derbyshire 739',
 '-38 41 Charlotte Marsden (164036) Hertfordshire 722 2',
 '-39 42 Alice Dillon (5036) Lancashire 719 1',
 '-43 43 Rana Rassem (178568) Durham 717',
 '-42 44 Nicole Scott (3589) Northen Ireland 710',
 '-40 45 Anais O`connor (163985) Cheshire 709',
 '-44 46 Chloe Lingard (90443) Lincolnshire 689 2',
 '-46 47 Alice Hazell (2491) Sussex 683',
 '-47 48 Casey Nickle (175867) Middlesex 670 1',
 '-49 49 Amillia Baker (170138) Staffordshire 668',
 '-48 50 Scarlett Anders (182173) Middlesex 662 2',
 '-50 51 Samadhi Udamulla (168711) Hertfordshire 634',
 '-51 52 Sophie Newton (165255) Lancashire 633',
 '-56 53 Megan Jones (178314) Shropshire 632',
 '-53 54 Jodie Morris (180375) Sussex 626 1',
 '-52 55 Angharad Beman (168018) Devonshire 625',
 '-54 56 Medha Verma (4145) Surrey 617',
 '-55 57 Morgan Davies (184083) Wales 612',
 '-70 58 Anna Green (156731) Nottinghamshire 588',
 '-64 59 Lauren Loosemore (182770) Devonshire 572',
 '-62 60 Temeesha Hobbs (158614) IsleOfWightTTA 559',
 '-57 61 Anya Milne (175569) Durham 557',
 '-58 62 Pelin Karabulut (178343) Oxfordshire 557',
 '-59 63 Jemma Walker (217) Buckinghamshire 546 4',
 '-60 64 Aimee Evans (2482) Staffordshire 541 1',
 '-61 65 Niamh Scarborough (184178) Cheshire 538',
 '-66 66 Ella Barnard (175316) Norfolk 529',
 '-63 67 Nicole Larmour (196407) Northen Ireland 525 2',
 '-67 68 Sophie Rinnhofer (154440) Warwickshire 524',
 '-65 69 Rebecca Savage (177006) Durham 519',
 '-68 70 Nikka Zareh (188155) Middlesex 471 2',
 '-69 71 Lucy McIvor (200732) Northen Ireland 470 2',
 '-94 72 Stefania Popa (173604) Lincolnshire 464',
 '-72 73 Wiktoria Smolarek (180185) Scotland 451',
 '-73 74 Amy Mold (184709) Durham 446 2',
 '-74 75 Pravesha Ragi (197346) Ireland 441 1',
 '-71 76 Lucy Vernon (174988) Derbyshire 438',
 '-95 77 Yuvathi Vijay (178608) India 433',
 '-79 78 Natasha Johnston (7282) Nottinghamshire 422',
 '-76 79 Joelle Bennett (235) Sussex 410',
 '-77 80 Emily Beasley (162742) Warwickshire 409 1-81 81 Jyothirmayi Vaishnavi Ghanta (191086) Berkshire 407',
 '-78 82 Shristi Ghosh (3093) Buckinghamshire 399',
 '-75 83 Bethan Jones (190888) Wales 399',
 '-80 84 Aakanksha Tripathi (153262) Lancashire 397 1',
 '-82 85 Bethany Brewer (95253) Wales 384 2',
 '-83 86 Victoria Coll (1183) Oxfordshire 375 1',
 '-84 87 Konstantina Apostologianni (186298) Lancashire 374 2',
 '-86 88 Katie Bates (178432) ClevelandTTA 373',
 '-88 89 Isabelle Lacorte (182285) Hertfordshire 369 1',
 '-85 90 Isobella Khan (172697) Avon 364',
 '-102 91 Abbie Hurley (180556) Kent 363',
 '-87 92 Catherine Balshaw (176142) Yorkshire 361',
 '-90 93 Lola McGhee (176099) ClevelandTTA 358 2',
 '-89 94 Paula Callaghan (193633) Scotland 358',
 '-91 95 Alexandra Robinson (7663) Lincolnshire 357 2',
 '-92 96 Aimey Gerald (169021) Middlesex 351 2',
 '-99 97 Anna Maria Besarabova (170467) Bulgaria 351',
 '-93 98 Milly Green (162815) Warwickshire 349 2',
 '-96 99 Katie Christoforou (186657) Lincolnshire 346 4',
 '-97 100 Eve Witterick (166744) ClevelandTTA 343',
 '-98 101 Maliha Baig (182658) Essex 341 1',
 '-100 102 Sophie Barcsai (183502) Dorset 334 1',
 '-101 103 Anna Kelly (200733) Northen Ireland 332 2',
 '-103 104 Zoe Bennett (157474) Devonshire 319',
 '-104 105 Rebecca Rigg (173418) Cumbria-TableTennisEngland 312',
 '-105 106 Lok Yee (jade) Ngan (193266) China 308 1',
 '-106 107 Jasmin Coker (193961) Derbyshire 302',
 '-108 108 Talia Banin-Reid (2904) Middlesex 294 4',
 '-109 109 Evelyn Pace (198287) Surrey 290',
 '-107 110 Lucy Curtis (165026) Suffolk 283',
 '-116 111 Sarah Amin (176784) Yorkshire 283',
 '-110 112 Chloe Pryke (164286) Cambridgeshire 281 1',
 '-114 113 Isobel McGerty (170470) Suffolk 281',
 '-111 114 Nicola Dawson (162995) Kent 272 2',
 '-115 115 Riya Kumar (151795) Suffolk 269 1',
 '-112 116 Min Jie Guo (54343) Kent 261',
 '-113 117 Mukmanee Warburton (168175) Yorkshire 261 1',
 '-117 118 Isabel Webb (59299) Kent 256',
 '-118 119 Ruby Bennett (182233) Cheshire 233 2',
 '-119 120 Ebony Hempsell (194373) Yorkshire 222 1',
 '-120 121 Reem Rassem (180472) Durham 212',
 '-121 122 Edith Dedman (177938) Dorset 210 3',
 '-122 123 Ciara Hancox (164804) Warwickshire 208 2',
 '-133 124 Connie Dumelow (190110) Derbyshire 201',
 '-134 125 Anna Piercey (190241) Buckinghamshire 200',
 '-124 126 Darcy Brewer (177360) Norfolk 196',
 '-125 127 Nina Oliva (189966) Kent 196 3',
 '-126 128 Anna Wilson (166137) Northamptonshire 193 2',
 '-130 129 Kate Watkinson (184531) Lancashire 193',
 "-127 130 Sasha O'Halloran (184193) Sussex 192",
 '-123 131 Bethany Wootton (163506) Staffordshire 184',
 '-132 132 Ellesse Trangmar (187934) - 183 4',
 '-129 133 Emily Ravetto (186960) - 182 2',
 '-141 134 Rachael Iles (196802) Buckinghamshire 178',
 '-153 135 Eleanor Fletcher (174251) Warwickshire 175',
 '-135 136 Abigail Ingles (173605) Worcestershire 172 4',
 '-136 137 Ella Stanton (186003) Dorset 170',
 '-128 138 Karishma Shah (179769) Surrey 169 2',
 '-138 139 Saskia Key (175113) Kent 167',
 '-146 140 Inderjeet Pawar (191091) - 167',
 '-139 141 Constance Reynolds (187312) Hertfordshire 165',
 '-145 142 Heidi Oestreicher (191095) Bedfordshire 164',
 '-140 143 Sienna Jetha (189584) Middlesex 161',
 '(-) 144 Naziyah Hasan (200915) Surrey 157',
 '-147 145 Lucy Needham (180481) Suffolk 146',
 '(-) 146 Millie Flannagan (187976) Middlesex 145 2',
 '-143 147 Rosa McKechnie (177936) Dorset 143 2',
 '-151 148 Emily Koester (190228) - 141',
 '-142 149 Jessica Moggeridge (182117) Dorset 139',
 '-144 150 Georgia Barker (184025) Hampshire 136 3',
 '-148 151 Mia Charles (186189) - 135',
 '-149 152 Amalia Stern (188212) Wiltshire 122 2',
 '-150 153 Shaniely Edwards (191936) Bedfordshire 118',
 '-161 154 Libby Hudson (185758) Kent 117',
 '-156 155 Natasha Richardson (184303) - 115',
 '-152 156 Chloe Kay (180047) Devonshire 110 1',
 '-154 157 Anna Cole (183288) Worcestershire 107',
 '-155 158 Sophie Arrandale (188478) - 101',
 '-158 159 Milly Hanrahan (189394) Cheshire 92',
 '-166 160 Edie Huckel (189177) - 91',
 '-159 161 Bethany Ellis (176155) Lancashire 88',
 '-157 162 Holly Davis (179712) Cornwall 87-160 163 Claudia Hough (180634) - 79 1',
 '-162 164 Hannah Silcock (197105) Jersey 64',
 '-163 165 Gypsie Kay (180048) Devonshire 63 1',
 '-164 166 Lilli Foreman (192073) Oxfordshire 63',
 '-165 167 Olivia Jones (90514) Essex 55 1',
 '-167 168 Holly Calton (192251) Dorset 34',
 '-168 169 Jodie Robertson (189866) - 14 1',
 '-169 170 Lucie Smith (167203) SouthYorkshire 13 2Junior Boys']

In [637]:
LforCrateInformationofPlayer[0].split(' ')

['-2', '1', 'Charlotte', 'Bardsley', '(163059)', 'Staffordshire', '1488']

In [638]:
for i in range(len(LforCrateInformationofPlayer)):
    if(len(LforCrateInformationofPlayer[i].split(' '))>8):
        print(LforCrateInformationofPlayer[i].split(' '))
        print(LforCrateInformationofPlayer[i],i,'&&&&',len(LforCrateInformationofPlayer[i].split(' ')))

['-63', '67', 'Nicole', 'Larmour', '(196407)', 'Northen', 'Ireland', '525', '2']
-63 67 Nicole Larmour (196407) Northen Ireland 525 2 66 &&&& 9
['-69', '71', 'Lucy', 'McIvor', '(200732)', 'Northen', 'Ireland', '470', '2']
-69 71 Lucy McIvor (200732) Northen Ireland 470 2 70 &&&& 9
['-77', '80', 'Emily', 'Beasley', '(162742)', 'Warwickshire', '409', '1-81', '81', 'Jyothirmayi', 'Vaishnavi', 'Ghanta', '(191086)', 'Berkshire', '407']
-77 80 Emily Beasley (162742) Warwickshire 409 1-81 81 Jyothirmayi Vaishnavi Ghanta (191086) Berkshire 407 79 &&&& 15
['-101', '103', 'Anna', 'Kelly', '(200733)', 'Northen', 'Ireland', '332', '2']
-101 103 Anna Kelly (200733) Northen Ireland 332 2 101 &&&& 9
['-105', '106', 'Lok', 'Yee', '(jade)', 'Ngan', '(193266)', 'China', '308', '1']
-105 106 Lok Yee (jade) Ngan (193266) China 308 1 104 &&&& 10
['-157', '162', 'Holly', 'Davis', '(179712)', 'Cornwall', '87-160', '163', 'Claudia', 'Hough', '(180634)', '-', '79', '1']
-157 162 Holly Davis (179712) Cornwall 87-160 163 Claudia Hough (180634) - 79 1 160 &&&& 14
['-169', '170', 'Lucie', 'Smith', '(167203)', 'SouthYorkshire', '13', '2Junior', 'Boys']
-169 170 Lucie Smith (167203) SouthYorkshire 13 2Junior Boys 167 &&&& 9

In [639]:
LforCrateInformationofPlayer[2].split(' ')

['-3', '3', 'Jasmin', 'Wong', '(165375)', 'Yorkshire', '1300']

In [640]:
def CreatLforOnePlayer(L):
    LEN = len(L)
    ans=[]
    print(L)
    indexArrayofBrackets=[]
    for j in range(1,len(L)):
        if(L[j].find('(')>-1 or L[j].find(')')>-1):
            if(L[j][1:-1].isdigit()):
                indexArrayofBrackets.append(j)
    print(indexArrayofBrackets)
    if(len(indexArrayofBrackets)==1):
        if(L[0].find('(-)')>-1):
            ans.append(0)
        else:
            ans.append(int(L[0][1:]))
        ans.append(int(L[1]))
        nameP=''
        for k in range(2,indexArrayofBrackets[0]-1):
            nameP =nameP + L[k] + ' '
        nameP = nameP + L[indexArrayofBrackets[0]-1]
        ans.append(nameP)
        ans.append(int(L[indexArrayofBrackets[0]][1:-1]))
        print('HAlf L = ',ans)
        countyP=''
        if(len(L[-1])==1):
            for x in range(indexArrayofBrackets[0]+1,len(L)-3):
                countyP = countyP + L[x] + ' '
            countyP = countyP + L[len(L)-3]
            ans.append(countyP)
            ans.append(int(L[-2]))
            ans.append(int(L[-1]))
        if(len(L[-1])>1):
            for x in range(indexArrayofBrackets[0]+1,len(L)-2):
                countyP = countyP + L[x] + ' '
            countyP = countyP + L[len(L)-2]
            ans.append(countyP)
            ans.append(int(L[-1]))
            ans.append(0)
    if(len(indexArrayofBrackets)==2):
        ans1=[]
        ans2=[]
        midRowIndex=0
        for i1 in range(1,len(L)):
            if(L[i1].find('-')>-1):
                midRowIndex= i1
                break
        print(midRowIndex,L[midRowIndex],'%%',indexArrayofBrackets)
        if(L[0].find('(-)')>-1):
            ans1.append(0)
        else:
            ans1.append(int(L[0][1:]))
        ans1.append(int(L[1]))
        nameP1=''
        nameP2=''
        countyP1=''
        countyP2=''
        for j1 in range(2,indexArrayofBrackets[0]-1):
            nameP1 = nameP1 + L[j1] + ' '
        nameP1 = nameP1 + L[indexArrayofBrackets[0]-1]
        ans1.append(nameP1)
        ans1.append(int(L[indexArrayofBrackets[0]][1:-1]))
        LastStringofP1 = L[midRowIndex][:L[midRowIndex].find('-')]
        FirstStringofP2 = L[midRowIndex][L[midRowIndex].find('-')+1:]
        print(ans1,LastStringofP1,FirstStringofP2)
        Difference = midRowIndex - indexArrayofBrackets[0]
        print(Difference,midRowIndex,indexArrayofBrackets[0])
        if(Difference==2):
            print('In difference 1....')
            ans1.append(L[midRowIndex-1])
            print(L[midRowIndex-1])
            ans1.append(int(LastStringofP1))
            ans1.append(0)
        if(Difference==3):
            print('In Differenc 2....')
            if(len(LastStringofP1)==1):
                ans1.append(L[midRowIndex-2])
                ans1.append(int(L[midRowIndex-1]))
                ans1.append(int(LastStringofP1))
            if(len(LastStringofP1)>1):
                ans1.append(L[midRowIndex-2]+ ' '+ L[midRowIndex-1])
                ans1.append(int(LastStringofP1))
                ans1.append(0)
        if(Difference>3):
            print('In difference morethan 2...')
            if(len(LastStringofP1)==1):
                for d1 in range(indexArrayofBrackets[0]+1,midRowIndex-2):
                    countyP1 = countyP1+L[d1]+' '
                countyP1 = countyP1 + L[midRowIndex-2]
                ans1.append(countyP1)
                ans1.append(int(L[midRowIndex-1]))
                ans1.append(int(LastStringofP1))
            if(len(LastStringofP1)>1):
                for d1 in range(indexArrayofBrackets[0]+1,midRowIndex-1):
                    countyP1 = countyP1 + L[d1]+ ' '
                countyP1 = countyP1+L[midRowIndex-1]
                ans1.append(countyP1)
                ans1.append(int(LastStringofP1))
                ans1.append(0)
        print('Ans1 = ',ans1)
        print('First String of P2 ',FirstStringofP2,'Last of P1 ',LastStringofP1,'Mid = ',L[11])
        if(FirstStringofP2.find('(-)')>-1):
            ans2.append(0)
        else:
            ans2.append(int(FirstStringofP2))
        ans2.append(int(L[midRowIndex+1]))
        for j1 in range(midRowIndex+2,indexArrayofBrackets[1]-1):
            nameP2 = nameP2 + L[j1] + ' '
        nameP2 = nameP2 + L[indexArrayofBrackets[1]-1]
        ans2.append(nameP2)
        ans2.append(int(L[indexArrayofBrackets[1]][1:-1]))

        Difference2 = (len(L)-1) - indexArrayofBrackets[1]
        print(Difference2,len(L),indexArrayofBrackets[1])
        if(Difference2==2):
            print('In difference 1....')
            ans2.append(L[-2])
            print(L[-2])
            ans2.append(int(L[-1]))
            ans2.append(0)
        if(Difference2==3):
            print('In Differenc 2....')
            if(len(L[-1])==1):
                ans2.append(L[-3])
                ans2.append(int(L[-2]))
                ans2.append(int(L[-1]))
            if(len(L[-1])>1):
                ans2.append(L[-3]+ ' '+ L[-2])
                ans2.append(int(L[-1]))
                ans2.append(0)
        if(Difference2>3):
            print('In difference morethan 2...')
            if(len(L[-1])==1):
                for d1 in range(indexArrayofBrackets[1]+1,len(L)-3):
                    countyP2 = countyP2+L[d1]+' '
                countyP2 = countyP2 + L[-3]
                ans2.append(countyP1)
                ans2.append(int(L[-2]))
                ans2.append(int(L[-1]))
            if(len(L[-1])>1):
                for d1 in range(indexArrayofBrackets[1]+1,len(L)-2):
                    countyP2 = countyP2 + L[d1]+ ' '
                countyP2 = countyP2+L[midRowIndex-1]
                ans2.append(countyP1)
                ans2.append(int(L[-1]))
                ans2.append(0)


        print('Ans2 = ',ans2)
        ans.append(ans1)
        ans.append(ans2)
    return ans

In [641]:
LforCrateInformationofPlayer[160].split(' ')

['-157',
 '162',
 'Holly',
 'Davis',
 '(179712)',
 'Cornwall',
 '87-160',
 '163',
 'Claudia',
 'Hough',
 '(180634)',
 '-',
 '79',
 '1']

In [642]:
CreatLforOnePlayer(LforCrateInformationofPlayer[160].split(' '))

['-157', '162', 'Holly', 'Davis', '(179712)', 'Cornwall', '87-160', '163', 'Claudia', 'Hough', '(180634)', '-', '79', '1']
[4, 10]
6 87-160 %% [4, 10]
[157, 162, 'Holly Davis', 179712] 87 160
2 6 4
In difference 1....
Cornwall
Ans1 =  [157, 162, 'Holly Davis', 179712, 'Cornwall', 87, 0]
First String of P2  160 Last of P1  87 Mid =  -
3 14 10
In Differenc 2....
Ans2 =  [160, 163, 'Claudia Hough', 180634, '-', 79, 1]

[[157, 162, 'Holly Davis', 179712, 'Cornwall', 87, 0],
 [160, 163, 'Claudia Hough', 180634, '-', 79, 1]]

In [643]:
LLforXLS=[]
for i in range(len(LforCrateInformationofPlayer)-1):
    print(i)
    LLforXLS.append(CreatLforOnePlayer(LforCrateInformationofPlayer[i].split(' ')))

0
['-2', '1', 'Charlotte', 'Bardsley', '(163059)', 'Staffordshire', '1488']
[4]
HAlf L =  [2, 1, 'Charlotte Bardsley', 163059]
1
['-1', '2', 'Denise', 'Payet', '(1344)', 'Middlesex', '1474', '1']
[4]
HAlf L =  [1, 2, 'Denise Payet', 1344]
2
['-3', '3', 'Jasmin', 'Wong', '(165375)', 'Yorkshire', '1300']
[4]
HAlf L =  [3, 3, 'Jasmin Wong', 165375]
3
['-4', '4', 'Mollie', 'Patterson', '(446)', 'Norfolk', '1257']
[4]
HAlf L =  [4, 4, 'Mollie Patterson', 446]
4
['-5', '5', 'Darcie', 'Proud', '(90566)', 'Lincolnshire', '1188']
[4]
HAlf L =  [5, 5, 'Darcie Proud', 90566]
5
['-6', '6', 'Anna', 'Hursey', '(6482)', 'Wales', '1175']
[4]
HAlf L =  [6, 6, 'Anna Hursey', 6482]
6
['-7', '7', 'Annie', 'Hedlund', '(198701)', 'Sweden', '1171', '2']
[4]
HAlf L =  [7, 7, 'Annie Hedlund', 198701]
7
['-8', '8', 'Megan', 'Gidney', '(172935)', 'Lancashire', '1158']
[4]
HAlf L =  [8, 8, 'Megan Gidney', 172935]
8
['-10', '9', 'Beth', 'Richards', '(170063)', 'Wales', '1106']
[4]
HAlf L =  [10, 9, 'Beth Richards', 170063]
9
['-9', '10', 'Gauri', 'Duhan', '(5655)', 'Yorkshire', '1070']
[4]
HAlf L =  [9, 10, 'Gauri Duhan', 5655]
10
['-16', '11', 'Danielle', 'Kelly', '(80573)', 'Wales', '1053']
[4]
HAlf L =  [16, 11, 'Danielle Kelly', 80573]
11
['-12', '12', 'Ruby', 'Chan', '(157565)', 'Yorkshire', '1033']
[4]
HAlf L =  [12, 12, 'Ruby Chan', 157565]
12
['-14', '13', 'Natalia', 'Ianau', '(167173)', 'Middlesex', '1012']
[4]
HAlf L =  [14, 13, 'Natalia Ianau', 167173]
13
['-20', '14', 'Mari', 'Baldwin', '(175928)', 'Devonshire', '1012']
[4]
HAlf L =  [20, 14, 'Mari Baldwin', 175928]
14
['-11', '15', 'Tiana', 'Dennison', '(3289)', 'Essex', '1011']
[4]
HAlf L =  [11, 15, 'Tiana Dennison', 3289]
15
['-13', '16', 'Gemma', 'Kerr', '(165956)', 'Devonshire', '992']
[4]
HAlf L =  [13, 16, 'Gemma Kerr', 165956]
16
['-15', '17', 'Anaya', 'Patel', '(172772)', 'Berkshire', '991']
[4]
HAlf L =  [15, 17, 'Anaya Patel', 172772]
17
['-21', '18', 'Lara', 'Whitton', '(166275)', 'Wales', '983']
[4]
HAlf L =  [21, 18, 'Lara Whitton', 166275]
18
['-19', '19', 'Katie', 'Holt', '(3128)', 'Dorset', '980']
[4]
HAlf L =  [19, 19, 'Katie Holt', 3128]
19
['-17', '20', 'Nomin', 'Baasan', '(192519)', 'Sweden', '972', '2']
[4]
HAlf L =  [17, 20, 'Nomin Baasan', 192519]
20
['-18', '21', 'Millie', 'Rogove', '(180435)', 'Hertfordshire', '970']
[4]
HAlf L =  [18, 21, 'Millie Rogove', 180435]
21
['-23', '22', 'Bhavika', 'Mistry', '(8564)', 'Northamptonshire', '908']
[4]
HAlf L =  [23, 22, 'Bhavika Mistry', 8564]
22
['-25', '23', 'Lydia', 'John', '(4765)', 'Wales', '884']
[4]
HAlf L =  [25, 23, 'Lydia John', 4765]
23
['-22', '24', 'Lois', 'Perryman', '(281)', 'Middlesex', '883']
[4]
HAlf L =  [22, 24, 'Lois Perryman', 281]
24
['-24', '25', 'Raquel', 'São', 'Pedro', '(186977)', 'Lincolnshire', '874']
[5]
HAlf L =  [24, 25, 'Raquel São Pedro', 186977]
25
['-26', '26', 'Sandy', 'Choong', '(191450)', 'Lancashire', '861', '1']
[4]
HAlf L =  [26, 26, 'Sandy Choong', 191450]
26
['-28', '27', 'Erin', 'Green', '(156732)', 'Nottinghamshire', '852']
[4]
HAlf L =  [28, 27, 'Erin Green', 156732]
27
['-27', '28', 'Sophie', 'Barlow', '(9039)', 'ClevelandTTA', '851', '2']
[4]
HAlf L =  [27, 28, 'Sophie Barlow', 9039]
28
['-30', '29', 'Grace', 'Clement', '(176566)', 'Wales', '828']
[4]
HAlf L =  [30, 29, 'Grace Clement', 176566]
29
['-31', '30', 'Charlotte', 'Weatherby', '(2137)', 'Durham', '826']
[4]
HAlf L =  [31, 30, 'Charlotte Weatherby', 2137]
30
['(-)', '31', 'Lauren', 'Stacey', '(168508)', 'Wales', '814']
[4]
HAlf L =  [0, 31, 'Lauren Stacey', 168508]
31
['-29', '32', 'Gracie', 'Edwards', '(3426)', 'Essex', '799']
[4]
HAlf L =  [29, 32, 'Gracie Edwards', 3426]
32
['-36', '33', 'Amy', 'Marriott', '(172447)', 'SouthYorkshire', '789']
[4]
HAlf L =  [36, 33, 'Amy Marriott', 172447]
33
['-41', '34', 'Emily', 'Haskell', '(7718)', 'Devonshire', '779']
[4]
HAlf L =  [41, 34, 'Emily Haskell', 7718]
34
['-35', '35', 'Kirsty', 'Maull', '(170245)', 'Staffordshire', '773']
[4]
HAlf L =  [35, 35, 'Kirsty Maull', 170245]
35
['-32', '36', 'Lucy', 'Craig', '(170952)', 'Northen', 'Ireland', '769']
[4]
HAlf L =  [32, 36, 'Lucy Craig', 170952]
36
['-33', '37', 'Federica', 'Bonato', '(8007)', 'Surrey', '759']
[4]
HAlf L =  [33, 37, 'Federica Bonato', 8007]
37
['-37', '38', 'Jamie-Lee', 'Harley', '(95252)', 'Wales', '754']
[4]
HAlf L =  [37, 38, 'Jamie-Lee Harley', 95252]
38
['-45', '39', 'Scarlett', "O'Neil", '(159169)', 'Kent', '753']
[4]
HAlf L =  [45, 39, "Scarlett O'Neil", 159169]
39
['-34', '40', 'Helena', 'Dicken', '(165503)', 'Derbyshire', '739']
[4]
HAlf L =  [34, 40, 'Helena Dicken', 165503]
40
['-38', '41', 'Charlotte', 'Marsden', '(164036)', 'Hertfordshire', '722', '2']
[4]
HAlf L =  [38, 41, 'Charlotte Marsden', 164036]
41
['-39', '42', 'Alice', 'Dillon', '(5036)', 'Lancashire', '719', '1']
[4]
HAlf L =  [39, 42, 'Alice Dillon', 5036]
42
['-43', '43', 'Rana', 'Rassem', '(178568)', 'Durham', '717']
[4]
HAlf L =  [43, 43, 'Rana Rassem', 178568]
43
['-42', '44', 'Nicole', 'Scott', '(3589)', 'Northen', 'Ireland', '710']
[4]
HAlf L =  [42, 44, 'Nicole Scott', 3589]
44
['-40', '45', 'Anais', 'O`connor', '(163985)', 'Cheshire', '709']
[4]
HAlf L =  [40, 45, 'Anais O`connor', 163985]
45
['-44', '46', 'Chloe', 'Lingard', '(90443)', 'Lincolnshire', '689', '2']
[4]
HAlf L =  [44, 46, 'Chloe Lingard', 90443]
46
['-46', '47', 'Alice', 'Hazell', '(2491)', 'Sussex', '683']
[4]
HAlf L =  [46, 47, 'Alice Hazell', 2491]
47
['-47', '48', 'Casey', 'Nickle', '(175867)', 'Middlesex', '670', '1']
[4]
HAlf L =  [47, 48, 'Casey Nickle', 175867]
48
['-49', '49', 'Amillia', 'Baker', '(170138)', 'Staffordshire', '668']
[4]
HAlf L =  [49, 49, 'Amillia Baker', 170138]
49
['-48', '50', 'Scarlett', 'Anders', '(182173)', 'Middlesex', '662', '2']
[4]
HAlf L =  [48, 50, 'Scarlett Anders', 182173]
50
['-50', '51', 'Samadhi', 'Udamulla', '(168711)', 'Hertfordshire', '634']
[4]
HAlf L =  [50, 51, 'Samadhi Udamulla', 168711]
51
['-51', '52', 'Sophie', 'Newton', '(165255)', 'Lancashire', '633']
[4]
HAlf L =  [51, 52, 'Sophie Newton', 165255]
52
['-56', '53', 'Megan', 'Jones', '(178314)', 'Shropshire', '632']
[4]
HAlf L =  [56, 53, 'Megan Jones', 178314]
53
['-53', '54', 'Jodie', 'Morris', '(180375)', 'Sussex', '626', '1']
[4]
HAlf L =  [53, 54, 'Jodie Morris', 180375]
54
['-52', '55', 'Angharad', 'Beman', '(168018)', 'Devonshire', '625']
[4]
HAlf L =  [52, 55, 'Angharad Beman', 168018]
55
['-54', '56', 'Medha', 'Verma', '(4145)', 'Surrey', '617']
[4]
HAlf L =  [54, 56, 'Medha Verma', 4145]
56
['-55', '57', 'Morgan', 'Davies', '(184083)', 'Wales', '612']
[4]
HAlf L =  [55, 57, 'Morgan Davies', 184083]
57
['-70', '58', 'Anna', 'Green', '(156731)', 'Nottinghamshire', '588']
[4]
HAlf L =  [70, 58, 'Anna Green', 156731]
58
['-64', '59', 'Lauren', 'Loosemore', '(182770)', 'Devonshire', '572']
[4]
HAlf L =  [64, 59, 'Lauren Loosemore', 182770]
59
['-62', '60', 'Temeesha', 'Hobbs', '(158614)', 'IsleOfWightTTA', '559']
[4]
HAlf L =  [62, 60, 'Temeesha Hobbs', 158614]
60
['-57', '61', 'Anya', 'Milne', '(175569)', 'Durham', '557']
[4]
HAlf L =  [57, 61, 'Anya Milne', 175569]
61
['-58', '62', 'Pelin', 'Karabulut', '(178343)', 'Oxfordshire', '557']
[4]
HAlf L =  [58, 62, 'Pelin Karabulut', 178343]
62
['-59', '63', 'Jemma', 'Walker', '(217)', 'Buckinghamshire', '546', '4']
[4]
HAlf L =  [59, 63, 'Jemma Walker', 217]
63
['-60', '64', 'Aimee', 'Evans', '(2482)', 'Staffordshire', '541', '1']
[4]
HAlf L =  [60, 64, 'Aimee Evans', 2482]
64
['-61', '65', 'Niamh', 'Scarborough', '(184178)', 'Cheshire', '538']
[4]
HAlf L =  [61, 65, 'Niamh Scarborough', 184178]
65
['-66', '66', 'Ella', 'Barnard', '(175316)', 'Norfolk', '529']
[4]
HAlf L =  [66, 66, 'Ella Barnard', 175316]
66
['-63', '67', 'Nicole', 'Larmour', '(196407)', 'Northen', 'Ireland', '525', '2']
[4]
HAlf L =  [63, 67, 'Nicole Larmour', 196407]
67
['-67', '68', 'Sophie', 'Rinnhofer', '(154440)', 'Warwickshire', '524']
[4]
HAlf L =  [67, 68, 'Sophie Rinnhofer', 154440]
68
['-65', '69', 'Rebecca', 'Savage', '(177006)', 'Durham', '519']
[4]
HAlf L =  [65, 69, 'Rebecca Savage', 177006]
69
['-68', '70', 'Nikka', 'Zareh', '(188155)', 'Middlesex', '471', '2']
[4]
HAlf L =  [68, 70, 'Nikka Zareh', 188155]
70
['-69', '71', 'Lucy', 'McIvor', '(200732)', 'Northen', 'Ireland', '470', '2']
[4]
HAlf L =  [69, 71, 'Lucy McIvor', 200732]
71
['-94', '72', 'Stefania', 'Popa', '(173604)', 'Lincolnshire', '464']
[4]
HAlf L =  [94, 72, 'Stefania Popa', 173604]
72
['-72', '73', 'Wiktoria', 'Smolarek', '(180185)', 'Scotland', '451']
[4]
HAlf L =  [72, 73, 'Wiktoria Smolarek', 180185]
73
['-73', '74', 'Amy', 'Mold', '(184709)', 'Durham', '446', '2']
[4]
HAlf L =  [73, 74, 'Amy Mold', 184709]
74
['-74', '75', 'Pravesha', 'Ragi', '(197346)', 'Ireland', '441', '1']
[4]
HAlf L =  [74, 75, 'Pravesha Ragi', 197346]
75
['-71', '76', 'Lucy', 'Vernon', '(174988)', 'Derbyshire', '438']
[4]
HAlf L =  [71, 76, 'Lucy Vernon', 174988]
76
['-95', '77', 'Yuvathi', 'Vijay', '(178608)', 'India', '433']
[4]
HAlf L =  [95, 77, 'Yuvathi Vijay', 178608]
77
['-79', '78', 'Natasha', 'Johnston', '(7282)', 'Nottinghamshire', '422']
[4]
HAlf L =  [79, 78, 'Natasha Johnston', 7282]
78
['-76', '79', 'Joelle', 'Bennett', '(235)', 'Sussex', '410']
[4]
HAlf L =  [76, 79, 'Joelle Bennett', 235]
79
['-77', '80', 'Emily', 'Beasley', '(162742)', 'Warwickshire', '409', '1-81', '81', 'Jyothirmayi', 'Vaishnavi', 'Ghanta', '(191086)', 'Berkshire', '407']
[4, 12]
7 1-81 %% [4, 12]
[77, 80, 'Emily Beasley', 162742] 1 81
3 7 4
In Differenc 2....
Ans1 =  [77, 80, 'Emily Beasley', 162742, 'Warwickshire', 409, 1]
First String of P2  81 Last of P1  1 Mid =  Ghanta
2 15 12
In difference 1....
Berkshire
Ans2 =  [81, 81, 'Jyothirmayi Vaishnavi Ghanta', 191086, 'Berkshire', 407, 0]
80
['-78', '82', 'Shristi', 'Ghosh', '(3093)', 'Buckinghamshire', '399']
[4]
HAlf L =  [78, 82, 'Shristi Ghosh', 3093]
81
['-75', '83', 'Bethan', 'Jones', '(190888)', 'Wales', '399']
[4]
HAlf L =  [75, 83, 'Bethan Jones', 190888]
82
['-80', '84', 'Aakanksha', 'Tripathi', '(153262)', 'Lancashire', '397', '1']
[4]
HAlf L =  [80, 84, 'Aakanksha Tripathi', 153262]
83
['-82', '85', 'Bethany', 'Brewer', '(95253)', 'Wales', '384', '2']
[4]
HAlf L =  [82, 85, 'Bethany Brewer', 95253]
84
['-83', '86', 'Victoria', 'Coll', '(1183)', 'Oxfordshire', '375', '1']
[4]
HAlf L =  [83, 86, 'Victoria Coll', 1183]
85
['-84', '87', 'Konstantina', 'Apostologianni', '(186298)', 'Lancashire', '374', '2']
[4]
HAlf L =  [84, 87, 'Konstantina Apostologianni', 186298]
86
['-86', '88', 'Katie', 'Bates', '(178432)', 'ClevelandTTA', '373']
[4]
HAlf L =  [86, 88, 'Katie Bates', 178432]
87
['-88', '89', 'Isabelle', 'Lacorte', '(182285)', 'Hertfordshire', '369', '1']
[4]
HAlf L =  [88, 89, 'Isabelle Lacorte', 182285]
88
['-85', '90', 'Isobella', 'Khan', '(172697)', 'Avon', '364']
[4]
HAlf L =  [85, 90, 'Isobella Khan', 172697]
89
['-102', '91', 'Abbie', 'Hurley', '(180556)', 'Kent', '363']
[4]
HAlf L =  [102, 91, 'Abbie Hurley', 180556]
90
['-87', '92', 'Catherine', 'Balshaw', '(176142)', 'Yorkshire', '361']
[4]
HAlf L =  [87, 92, 'Catherine Balshaw', 176142]
91
['-90', '93', 'Lola', 'McGhee', '(176099)', 'ClevelandTTA', '358', '2']
[4]
HAlf L =  [90, 93, 'Lola McGhee', 176099]
92
['-89', '94', 'Paula', 'Callaghan', '(193633)', 'Scotland', '358']
[4]
HAlf L =  [89, 94, 'Paula Callaghan', 193633]
93
['-91', '95', 'Alexandra', 'Robinson', '(7663)', 'Lincolnshire', '357', '2']
[4]
HAlf L =  [91, 95, 'Alexandra Robinson', 7663]
94
['-92', '96', 'Aimey', 'Gerald', '(169021)', 'Middlesex', '351', '2']
[4]
HAlf L =  [92, 96, 'Aimey Gerald', 169021]
95
['-99', '97', 'Anna', 'Maria', 'Besarabova', '(170467)', 'Bulgaria', '351']
[5]
HAlf L =  [99, 97, 'Anna Maria Besarabova', 170467]
96
['-93', '98', 'Milly', 'Green', '(162815)', 'Warwickshire', '349', '2']
[4]
HAlf L =  [93, 98, 'Milly Green', 162815]
97
['-96', '99', 'Katie', 'Christoforou', '(186657)', 'Lincolnshire', '346', '4']
[4]
HAlf L =  [96, 99, 'Katie Christoforou', 186657]
98
['-97', '100', 'Eve', 'Witterick', '(166744)', 'ClevelandTTA', '343']
[4]
HAlf L =  [97, 100, 'Eve Witterick', 166744]
99
['-98', '101', 'Maliha', 'Baig', '(182658)', 'Essex', '341', '1']
[4]
HAlf L =  [98, 101, 'Maliha Baig', 182658]
100
['-100', '102', 'Sophie', 'Barcsai', '(183502)', 'Dorset', '334', '1']
[4]
HAlf L =  [100, 102, 'Sophie Barcsai', 183502]
101
['-101', '103', 'Anna', 'Kelly', '(200733)', 'Northen', 'Ireland', '332', '2']
[4]
HAlf L =  [101, 103, 'Anna Kelly', 200733]
102
['-103', '104', 'Zoe', 'Bennett', '(157474)', 'Devonshire', '319']
[4]
HAlf L =  [103, 104, 'Zoe Bennett', 157474]
103
['-104', '105', 'Rebecca', 'Rigg', '(173418)', 'Cumbria-TableTennisEngland', '312']
[4]
HAlf L =  [104, 105, 'Rebecca Rigg', 173418]
104
['-105', '106', 'Lok', 'Yee', '(jade)', 'Ngan', '(193266)', 'China', '308', '1']
[6]
HAlf L =  [105, 106, 'Lok Yee (jade) Ngan', 193266]
105
['-106', '107', 'Jasmin', 'Coker', '(193961)', 'Derbyshire', '302']
[4]
HAlf L =  [106, 107, 'Jasmin Coker', 193961]
106
['-108', '108', 'Talia', 'Banin-Reid', '(2904)', 'Middlesex', '294', '4']
[4]
HAlf L =  [108, 108, 'Talia Banin-Reid', 2904]
107
['-109', '109', 'Evelyn', 'Pace', '(198287)', 'Surrey', '290']
[4]
HAlf L =  [109, 109, 'Evelyn Pace', 198287]
108
['-107', '110', 'Lucy', 'Curtis', '(165026)', 'Suffolk', '283']
[4]
HAlf L =  [107, 110, 'Lucy Curtis', 165026]
109
['-116', '111', 'Sarah', 'Amin', '(176784)', 'Yorkshire', '283']
[4]
HAlf L =  [116, 111, 'Sarah Amin', 176784]
110
['-110', '112', 'Chloe', 'Pryke', '(164286)', 'Cambridgeshire', '281', '1']
[4]
HAlf L =  [110, 112, 'Chloe Pryke', 164286]
111
['-114', '113', 'Isobel', 'McGerty', '(170470)', 'Suffolk', '281']
[4]
HAlf L =  [114, 113, 'Isobel McGerty', 170470]
112
['-111', '114', 'Nicola', 'Dawson', '(162995)', 'Kent', '272', '2']
[4]
HAlf L =  [111, 114, 'Nicola Dawson', 162995]
113
['-115', '115', 'Riya', 'Kumar', '(151795)', 'Suffolk', '269', '1']
[4]
HAlf L =  [115, 115, 'Riya Kumar', 151795]
114
['-112', '116', 'Min', 'Jie', 'Guo', '(54343)', 'Kent', '261']
[5]
HAlf L =  [112, 116, 'Min Jie Guo', 54343]
115
['-113', '117', 'Mukmanee', 'Warburton', '(168175)', 'Yorkshire', '261', '1']
[4]
HAlf L =  [113, 117, 'Mukmanee Warburton', 168175]
116
['-117', '118', 'Isabel', 'Webb', '(59299)', 'Kent', '256']
[4]
HAlf L =  [117, 118, 'Isabel Webb', 59299]
117
['-118', '119', 'Ruby', 'Bennett', '(182233)', 'Cheshire', '233', '2']
[4]
HAlf L =  [118, 119, 'Ruby Bennett', 182233]
118
['-119', '120', 'Ebony', 'Hempsell', '(194373)', 'Yorkshire', '222', '1']
[4]
HAlf L =  [119, 120, 'Ebony Hempsell', 194373]
119
['-120', '121', 'Reem', 'Rassem', '(180472)', 'Durham', '212']
[4]
HAlf L =  [120, 121, 'Reem Rassem', 180472]
120
['-121', '122', 'Edith', 'Dedman', '(177938)', 'Dorset', '210', '3']
[4]
HAlf L =  [121, 122, 'Edith Dedman', 177938]
121
['-122', '123', 'Ciara', 'Hancox', '(164804)', 'Warwickshire', '208', '2']
[4]
HAlf L =  [122, 123, 'Ciara Hancox', 164804]
122
['-133', '124', 'Connie', 'Dumelow', '(190110)', 'Derbyshire', '201']
[4]
HAlf L =  [133, 124, 'Connie Dumelow', 190110]
123
['-134', '125', 'Anna', 'Piercey', '(190241)', 'Buckinghamshire', '200']
[4]
HAlf L =  [134, 125, 'Anna Piercey', 190241]
124
['-124', '126', 'Darcy', 'Brewer', '(177360)', 'Norfolk', '196']
[4]
HAlf L =  [124, 126, 'Darcy Brewer', 177360]
125
['-125', '127', 'Nina', 'Oliva', '(189966)', 'Kent', '196', '3']
[4]
HAlf L =  [125, 127, 'Nina Oliva', 189966]
126
['-126', '128', 'Anna', 'Wilson', '(166137)', 'Northamptonshire', '193', '2']
[4]
HAlf L =  [126, 128, 'Anna Wilson', 166137]
127
['-130', '129', 'Kate', 'Watkinson', '(184531)', 'Lancashire', '193']
[4]
HAlf L =  [130, 129, 'Kate Watkinson', 184531]
128
['-127', '130', 'Sasha', "O'Halloran", '(184193)', 'Sussex', '192']
[4]
HAlf L =  [127, 130, "Sasha O'Halloran", 184193]
129
['-123', '131', 'Bethany', 'Wootton', '(163506)', 'Staffordshire', '184']
[4]
HAlf L =  [123, 131, 'Bethany Wootton', 163506]
130
['-132', '132', 'Ellesse', 'Trangmar', '(187934)', '-', '183', '4']
[4]
HAlf L =  [132, 132, 'Ellesse Trangmar', 187934]
131
['-129', '133', 'Emily', 'Ravetto', '(186960)', '-', '182', '2']
[4]
HAlf L =  [129, 133, 'Emily Ravetto', 186960]
132
['-141', '134', 'Rachael', 'Iles', '(196802)', 'Buckinghamshire', '178']
[4]
HAlf L =  [141, 134, 'Rachael Iles', 196802]
133
['-153', '135', 'Eleanor', 'Fletcher', '(174251)', 'Warwickshire', '175']
[4]
HAlf L =  [153, 135, 'Eleanor Fletcher', 174251]
134
['-135', '136', 'Abigail', 'Ingles', '(173605)', 'Worcestershire', '172', '4']
[4]
HAlf L =  [135, 136, 'Abigail Ingles', 173605]
135
['-136', '137', 'Ella', 'Stanton', '(186003)', 'Dorset', '170']
[4]
HAlf L =  [136, 137, 'Ella Stanton', 186003]
136
['-128', '138', 'Karishma', 'Shah', '(179769)', 'Surrey', '169', '2']
[4]
HAlf L =  [128, 138, 'Karishma Shah', 179769]
137
['-138', '139', 'Saskia', 'Key', '(175113)', 'Kent', '167']
[4]
HAlf L =  [138, 139, 'Saskia Key', 175113]
138
['-146', '140', 'Inderjeet', 'Pawar', '(191091)', '-', '167']
[4]
HAlf L =  [146, 140, 'Inderjeet Pawar', 191091]
139
['-139', '141', 'Constance', 'Reynolds', '(187312)', 'Hertfordshire', '165']
[4]
HAlf L =  [139, 141, 'Constance Reynolds', 187312]
140
['-145', '142', 'Heidi', 'Oestreicher', '(191095)', 'Bedfordshire', '164']
[4]
HAlf L =  [145, 142, 'Heidi Oestreicher', 191095]
141
['-140', '143', 'Sienna', 'Jetha', '(189584)', 'Middlesex', '161']
[4]
HAlf L =  [140, 143, 'Sienna Jetha', 189584]
142
['(-)', '144', 'Naziyah', 'Hasan', '(200915)', 'Surrey', '157']
[4]
HAlf L =  [0, 144, 'Naziyah Hasan', 200915]
143
['-147', '145', 'Lucy', 'Needham', '(180481)', 'Suffolk', '146']
[4]
HAlf L =  [147, 145, 'Lucy Needham', 180481]
144
['(-)', '146', 'Millie', 'Flannagan', '(187976)', 'Middlesex', '145', '2']
[4]
HAlf L =  [0, 146, 'Millie Flannagan', 187976]
145
['-143', '147', 'Rosa', 'McKechnie', '(177936)', 'Dorset', '143', '2']
[4]
HAlf L =  [143, 147, 'Rosa McKechnie', 177936]
146
['-151', '148', 'Emily', 'Koester', '(190228)', '-', '141']
[4]
HAlf L =  [151, 148, 'Emily Koester', 190228]
147
['-142', '149', 'Jessica', 'Moggeridge', '(182117)', 'Dorset', '139']
[4]
HAlf L =  [142, 149, 'Jessica Moggeridge', 182117]
148
['-144', '150', 'Georgia', 'Barker', '(184025)', 'Hampshire', '136', '3']
[4]
HAlf L =  [144, 150, 'Georgia Barker', 184025]
149
['-148', '151', 'Mia', 'Charles', '(186189)', '-', '135']
[4]
HAlf L =  [148, 151, 'Mia Charles', 186189]
150
['-149', '152', 'Amalia', 'Stern', '(188212)', 'Wiltshire', '122', '2']
[4]
HAlf L =  [149, 152, 'Amalia Stern', 188212]
151
['-150', '153', 'Shaniely', 'Edwards', '(191936)', 'Bedfordshire', '118']
[4]
HAlf L =  [150, 153, 'Shaniely Edwards', 191936]
152
['-161', '154', 'Libby', 'Hudson', '(185758)', 'Kent', '117']
[4]
HAlf L =  [161, 154, 'Libby Hudson', 185758]
153
['-156', '155', 'Natasha', 'Richardson', '(184303)', '-', '115']
[4]
HAlf L =  [156, 155, 'Natasha Richardson', 184303]
154
['-152', '156', 'Chloe', 'Kay', '(180047)', 'Devonshire', '110', '1']
[4]
HAlf L =  [152, 156, 'Chloe Kay', 180047]
155
['-154', '157', 'Anna', 'Cole', '(183288)', 'Worcestershire', '107']
[4]
HAlf L =  [154, 157, 'Anna Cole', 183288]
156
['-155', '158', 'Sophie', 'Arrandale', '(188478)', '-', '101']
[4]
HAlf L =  [155, 158, 'Sophie Arrandale', 188478]
157
['-158', '159', 'Milly', 'Hanrahan', '(189394)', 'Cheshire', '92']
[4]
HAlf L =  [158, 159, 'Milly Hanrahan', 189394]
158
['-166', '160', 'Edie', 'Huckel', '(189177)', '-', '91']
[4]
HAlf L =  [166, 160, 'Edie Huckel', 189177]
159
['-159', '161', 'Bethany', 'Ellis', '(176155)', 'Lancashire', '88']
[4]
HAlf L =  [159, 161, 'Bethany Ellis', 176155]
160
['-157', '162', 'Holly', 'Davis', '(179712)', 'Cornwall', '87-160', '163', 'Claudia', 'Hough', '(180634)', '-', '79', '1']
[4, 10]
6 87-160 %% [4, 10]
[157, 162, 'Holly Davis', 179712] 87 160
2 6 4
In difference 1....
Cornwall
Ans1 =  [157, 162, 'Holly Davis', 179712, 'Cornwall', 87, 0]
First String of P2  160 Last of P1  87 Mid =  -
3 14 10
In Differenc 2....
Ans2 =  [160, 163, 'Claudia Hough', 180634, '-', 79, 1]
161

In [644]:
LLforXLS

[[2, 1, 'Charlotte Bardsley', 163059, 'Staffordshire', 1488, 0],
 [1, 2, 'Denise Payet', 1344, 'Middlesex', 1474, 1],
 [3, 3, 'Jasmin Wong', 165375, 'Yorkshire', 1300, 0],
 [4, 4, 'Mollie Patterson', 446, 'Norfolk', 1257, 0],
 [5, 5, 'Darcie Proud', 90566, 'Lincolnshire', 1188, 0],
 [6, 6, 'Anna Hursey', 6482, 'Wales', 1175, 0],
 [7, 7, 'Annie Hedlund', 198701, 'Sweden', 1171, 2],
 [8, 8, 'Megan Gidney', 172935, 'Lancashire', 1158, 0],
 [10, 9, 'Beth Richards', 170063, 'Wales', 1106, 0],
 [9, 10, 'Gauri Duhan', 5655, 'Yorkshire', 1070, 0],
 [16, 11, 'Danielle Kelly', 80573, 'Wales', 1053, 0],
 [12, 12, 'Ruby Chan', 157565, 'Yorkshire', 1033, 0],
 [14, 13, 'Natalia Ianau', 167173, 'Middlesex', 1012, 0],
 [20, 14, 'Mari Baldwin', 175928, 'Devonshire', 1012, 0],
 [11, 15, 'Tiana Dennison', 3289, 'Essex', 1011, 0],
 [13, 16, 'Gemma Kerr', 165956, 'Devonshire', 992, 0],
 [15, 17, 'Anaya Patel', 172772, 'Berkshire', 991, 0],
 [21, 18, 'Lara Whitton', 166275, 'Wales', 983, 0],
 [19, 19, 'Katie Holt', 3128, 'Dorset', 980, 0],
 [17, 20, 'Nomin Baasan', 192519, 'Sweden', 972, 2],
 [18, 21, 'Millie Rogove', 180435, 'Hertfordshire', 970, 0],
 [23, 22, 'Bhavika Mistry', 8564, 'Northamptonshire', 908, 0],
 [25, 23, 'Lydia John', 4765, 'Wales', 884, 0],
 [22, 24, 'Lois Perryman', 281, 'Middlesex', 883, 0],
 [24, 25, 'Raquel São Pedro', 186977, 'Lincolnshire', 874, 0],
 [26, 26, 'Sandy Choong', 191450, 'Lancashire', 861, 1],
 [28, 27, 'Erin Green', 156732, 'Nottinghamshire', 852, 0],
 [27, 28, 'Sophie Barlow', 9039, 'ClevelandTTA', 851, 2],
 [30, 29, 'Grace Clement', 176566, 'Wales', 828, 0],
 [31, 30, 'Charlotte Weatherby', 2137, 'Durham', 826, 0],
 [0, 31, 'Lauren Stacey', 168508, 'Wales', 814, 0],
 [29, 32, 'Gracie Edwards', 3426, 'Essex', 799, 0],
 [36, 33, 'Amy Marriott', 172447, 'SouthYorkshire', 789, 0],
 [41, 34, 'Emily Haskell', 7718, 'Devonshire', 779, 0],
 [35, 35, 'Kirsty Maull', 170245, 'Staffordshire', 773, 0],
 [32, 36, 'Lucy Craig', 170952, 'Northen Ireland', 769, 0],
 [33, 37, 'Federica Bonato', 8007, 'Surrey', 759, 0],
 [37, 38, 'Jamie-Lee Harley', 95252, 'Wales', 754, 0],
 [45, 39, "Scarlett O'Neil", 159169, 'Kent', 753, 0],
 [34, 40, 'Helena Dicken', 165503, 'Derbyshire', 739, 0],
 [38, 41, 'Charlotte Marsden', 164036, 'Hertfordshire', 722, 2],
 [39, 42, 'Alice Dillon', 5036, 'Lancashire', 719, 1],
 [43, 43, 'Rana Rassem', 178568, 'Durham', 717, 0],
 [42, 44, 'Nicole Scott', 3589, 'Northen Ireland', 710, 0],
 [40, 45, 'Anais O`connor', 163985, 'Cheshire', 709, 0],
 [44, 46, 'Chloe Lingard', 90443, 'Lincolnshire', 689, 2],
 [46, 47, 'Alice Hazell', 2491, 'Sussex', 683, 0],
 [47, 48, 'Casey Nickle', 175867, 'Middlesex', 670, 1],
 [49, 49, 'Amillia Baker', 170138, 'Staffordshire', 668, 0],
 [48, 50, 'Scarlett Anders', 182173, 'Middlesex', 662, 2],
 [50, 51, 'Samadhi Udamulla', 168711, 'Hertfordshire', 634, 0],
 [51, 52, 'Sophie Newton', 165255, 'Lancashire', 633, 0],
 [56, 53, 'Megan Jones', 178314, 'Shropshire', 632, 0],
 [53, 54, 'Jodie Morris', 180375, 'Sussex', 626, 1],
 [52, 55, 'Angharad Beman', 168018, 'Devonshire', 625, 0],
 [54, 56, 'Medha Verma', 4145, 'Surrey', 617, 0],
 [55, 57, 'Morgan Davies', 184083, 'Wales', 612, 0],
 [70, 58, 'Anna Green', 156731, 'Nottinghamshire', 588, 0],
 [64, 59, 'Lauren Loosemore', 182770, 'Devonshire', 572, 0],
 [62, 60, 'Temeesha Hobbs', 158614, 'IsleOfWightTTA', 559, 0],
 [57, 61, 'Anya Milne', 175569, 'Durham', 557, 0],
 [58, 62, 'Pelin Karabulut', 178343, 'Oxfordshire', 557, 0],
 [59, 63, 'Jemma Walker', 217, 'Buckinghamshire', 546, 4],
 [60, 64, 'Aimee Evans', 2482, 'Staffordshire', 541, 1],
 [61, 65, 'Niamh Scarborough', 184178, 'Cheshire', 538, 0],
 [66, 66, 'Ella Barnard', 175316, 'Norfolk', 529, 0],
 [63, 67, 'Nicole Larmour', 196407, 'Northen Ireland', 525, 2],
 [67, 68, 'Sophie Rinnhofer', 154440, 'Warwickshire', 524, 0],
 [65, 69, 'Rebecca Savage', 177006, 'Durham', 519, 0],
 [68, 70, 'Nikka Zareh', 188155, 'Middlesex', 471, 2],
 [69, 71, 'Lucy McIvor', 200732, 'Northen Ireland', 470, 2],
 [94, 72, 'Stefania Popa', 173604, 'Lincolnshire', 464, 0],
 [72, 73, 'Wiktoria Smolarek', 180185, 'Scotland', 451, 0],
 [73, 74, 'Amy Mold', 184709, 'Durham', 446, 2],
 [74, 75, 'Pravesha Ragi', 197346, 'Ireland', 441, 1],
 [71, 76, 'Lucy Vernon', 174988, 'Derbyshire', 438, 0],
 [95, 77, 'Yuvathi Vijay', 178608, 'India', 433, 0],
 [79, 78, 'Natasha Johnston', 7282, 'Nottinghamshire', 422, 0],
 [76, 79, 'Joelle Bennett', 235, 'Sussex', 410, 0],
 [[77, 80, 'Emily Beasley', 162742, 'Warwickshire', 409, 1],
  [81, 81, 'Jyothirmayi Vaishnavi Ghanta', 191086, 'Berkshire', 407, 0]],
 [78, 82, 'Shristi Ghosh', 3093, 'Buckinghamshire', 399, 0],
 [75, 83, 'Bethan Jones', 190888, 'Wales', 399, 0],
 [80, 84, 'Aakanksha Tripathi', 153262, 'Lancashire', 397, 1],
 [82, 85, 'Bethany Brewer', 95253, 'Wales', 384, 2],
 [83, 86, 'Victoria Coll', 1183, 'Oxfordshire', 375, 1],
 [84, 87, 'Konstantina Apostologianni', 186298, 'Lancashire', 374, 2],
 [86, 88, 'Katie Bates', 178432, 'ClevelandTTA', 373, 0],
 [88, 89, 'Isabelle Lacorte', 182285, 'Hertfordshire', 369, 1],
 [85, 90, 'Isobella Khan', 172697, 'Avon', 364, 0],
 [102, 91, 'Abbie Hurley', 180556, 'Kent', 363, 0],
 [87, 92, 'Catherine Balshaw', 176142, 'Yorkshire', 361, 0],
 [90, 93, 'Lola McGhee', 176099, 'ClevelandTTA', 358, 2],
 [89, 94, 'Paula Callaghan', 193633, 'Scotland', 358, 0],
 [91, 95, 'Alexandra Robinson', 7663, 'Lincolnshire', 357, 2],
 [92, 96, 'Aimey Gerald', 169021, 'Middlesex', 351, 2],
 [99, 97, 'Anna Maria Besarabova', 170467, 'Bulgaria', 351, 0],
 [93, 98, 'Milly Green', 162815, 'Warwickshire', 349, 2],
 [96, 99, 'Katie Christoforou', 186657, 'Lincolnshire', 346, 4],
 [97, 100, 'Eve Witterick', 166744, 'ClevelandTTA', 343, 0],
 [98, 101, 'Maliha Baig', 182658, 'Essex', 341, 1],
 [100, 102, 'Sophie Barcsai', 183502, 'Dorset', 334, 1],
 [101, 103, 'Anna Kelly', 200733, 'Northen Ireland', 332, 2],
 [103, 104, 'Zoe Bennett', 157474, 'Devonshire', 319, 0],
 [104, 105, 'Rebecca Rigg', 173418, 'Cumbria-TableTennisEngland', 312, 0],
 [105, 106, 'Lok Yee (jade) Ngan', 193266, 'China', 308, 1],
 [106, 107, 'Jasmin Coker', 193961, 'Derbyshire', 302, 0],
 [108, 108, 'Talia Banin-Reid', 2904, 'Middlesex', 294, 4],
 [109, 109, 'Evelyn Pace', 198287, 'Surrey', 290, 0],
 [107, 110, 'Lucy Curtis', 165026, 'Suffolk', 283, 0],
 [116, 111, 'Sarah Amin', 176784, 'Yorkshire', 283, 0],
 [110, 112, 'Chloe Pryke', 164286, 'Cambridgeshire', 281, 1],
 [114, 113, 'Isobel McGerty', 170470, 'Suffolk', 281, 0],
 [111, 114, 'Nicola Dawson', 162995, 'Kent', 272, 2],
 [115, 115, 'Riya Kumar', 151795, 'Suffolk', 269, 1],
 [112, 116, 'Min Jie Guo', 54343, 'Kent', 261, 0],
 [113, 117, 'Mukmanee Warburton', 168175, 'Yorkshire', 261, 1],
 [117, 118, 'Isabel Webb', 59299, 'Kent', 256, 0],
 [118, 119, 'Ruby Bennett', 182233, 'Cheshire', 233, 2],
 [119, 120, 'Ebony Hempsell', 194373, 'Yorkshire', 222, 1],
 [120, 121, 'Reem Rassem', 180472, 'Durham', 212, 0],
 [121, 122, 'Edith Dedman', 177938, 'Dorset', 210, 3],
 [122, 123, 'Ciara Hancox', 164804, 'Warwickshire', 208, 2],
 [133, 124, 'Connie Dumelow', 190110, 'Derbyshire', 201, 0],
 [134, 125, 'Anna Piercey', 190241, 'Buckinghamshire', 200, 0],
 [124, 126, 'Darcy Brewer', 177360, 'Norfolk', 196, 0],
 [125, 127, 'Nina Oliva', 189966, 'Kent', 196, 3],
 [126, 128, 'Anna Wilson', 166137, 'Northamptonshire', 193, 2],
 [130, 129, 'Kate Watkinson', 184531, 'Lancashire', 193, 0],
 [127, 130, "Sasha O'Halloran", 184193, 'Sussex', 192, 0],
 [123, 131, 'Bethany Wootton', 163506, 'Staffordshire', 184, 0],
 [132, 132, 'Ellesse Trangmar', 187934, '-', 183, 4],
 [129, 133, 'Emily Ravetto', 186960, '-', 182, 2],
 [141, 134, 'Rachael Iles', 196802, 'Buckinghamshire', 178, 0],
 [153, 135, 'Eleanor Fletcher', 174251, 'Warwickshire', 175, 0],
 [135, 136, 'Abigail Ingles', 173605, 'Worcestershire', 172, 4],
 [136, 137, 'Ella Stanton', 186003, 'Dorset', 170, 0],
 [128, 138, 'Karishma Shah', 179769, 'Surrey', 169, 2],
 [138, 139, 'Saskia Key', 175113, 'Kent', 167, 0],
 [146, 140, 'Inderjeet Pawar', 191091, '-', 167, 0],
 [139, 141, 'Constance Reynolds', 187312, 'Hertfordshire', 165, 0],
 [145, 142, 'Heidi Oestreicher', 191095, 'Bedfordshire', 164, 0],
 [140, 143, 'Sienna Jetha', 189584, 'Middlesex', 161, 0],
 [0, 144, 'Naziyah Hasan', 200915, 'Surrey', 157, 0],
 [147, 145, 'Lucy Needham', 180481, 'Suffolk', 146, 0],
 [0, 146, 'Millie Flannagan', 187976, 'Middlesex', 145, 2],
 [143, 147, 'Rosa McKechnie', 177936, 'Dorset', 143, 2],
 [151, 148, 'Emily Koester', 190228, '-', 141, 0],
 [142, 149, 'Jessica Moggeridge', 182117, 'Dorset', 139, 0],
 [144, 150, 'Georgia Barker', 184025, 'Hampshire', 136, 3],
 [148, 151, 'Mia Charles', 186189, '-', 135, 0],
 [149, 152, 'Amalia Stern', 188212, 'Wiltshire', 122, 2],
 [150, 153, 'Shaniely Edwards', 191936, 'Bedfordshire', 118, 0],
 [161, 154, 'Libby Hudson', 185758, 'Kent', 117, 0],
 [156, 155, 'Natasha Richardson', 184303, '-', 115, 0],
 [152, 156, 'Chloe Kay', 180047, 'Devonshire', 110, 1],
 [154, 157, 'Anna Cole', 183288, 'Worcestershire', 107, 0],
 [155, 158, 'Sophie Arrandale', 188478, '-', 101, 0],
 [158, 159, 'Milly Hanrahan', 189394, 'Cheshire', 92, 0],
 [166, 160, 'Edie Huckel', 189177, '-', 91, 0],
 [159, 161, 'Bethany Ellis', 176155, 'Lancashire', 88, 0],
 [[157, 162, 'Holly Davis', 179712, 'Cornwall', 87, 0],
  [160, 163, 'Claudia Hough', 180634, '-', 79, 1]],
 [162, 164, 'Hannah Silcock', 197105, 'Jersey', 64, 0],
 [163, 165, 'Gypsie Kay', 180048, 'Devonshire', 63, 1],
 [164, 166, 'Lilli Foreman', 192073, 'Oxfordshire', 63, 0],
 [165, 167, 'Olivia Jones', 90514, 'Essex', 55, 1],
 [167, 168, 'Holly Calton', 192251, 'Dorset', 34, 0],
 [168, 169, 'Jodie Robertson', 189866, '-', 14, 1]]

In [645]:
LLforXLS.append(CreatLforOnePlayer(LforCrateInformationofPlayer[-1][:-11].split(' ')))

['-169', '170', 'Lucie', 'Smith', '(167203)', 'SouthYorkshire', '13', '2']
[4]
HAlf L =  [169, 170, 'Lucie Smith', 167203]

In [646]:
LLforXLS

[[2, 1, 'Charlotte Bardsley', 163059, 'Staffordshire', 1488, 0],
 [1, 2, 'Denise Payet', 1344, 'Middlesex', 1474, 1],
 [3, 3, 'Jasmin Wong', 165375, 'Yorkshire', 1300, 0],
 [4, 4, 'Mollie Patterson', 446, 'Norfolk', 1257, 0],
 [5, 5, 'Darcie Proud', 90566, 'Lincolnshire', 1188, 0],
 [6, 6, 'Anna Hursey', 6482, 'Wales', 1175, 0],
 [7, 7, 'Annie Hedlund', 198701, 'Sweden', 1171, 2],
 [8, 8, 'Megan Gidney', 172935, 'Lancashire', 1158, 0],
 [10, 9, 'Beth Richards', 170063, 'Wales', 1106, 0],
 [9, 10, 'Gauri Duhan', 5655, 'Yorkshire', 1070, 0],
 [16, 11, 'Danielle Kelly', 80573, 'Wales', 1053, 0],
 [12, 12, 'Ruby Chan', 157565, 'Yorkshire', 1033, 0],
 [14, 13, 'Natalia Ianau', 167173, 'Middlesex', 1012, 0],
 [20, 14, 'Mari Baldwin', 175928, 'Devonshire', 1012, 0],
 [11, 15, 'Tiana Dennison', 3289, 'Essex', 1011, 0],
 [13, 16, 'Gemma Kerr', 165956, 'Devonshire', 992, 0],
 [15, 17, 'Anaya Patel', 172772, 'Berkshire', 991, 0],
 [21, 18, 'Lara Whitton', 166275, 'Wales', 983, 0],
 [19, 19, 'Katie Holt', 3128, 'Dorset', 980, 0],
 [17, 20, 'Nomin Baasan', 192519, 'Sweden', 972, 2],
 [18, 21, 'Millie Rogove', 180435, 'Hertfordshire', 970, 0],
 [23, 22, 'Bhavika Mistry', 8564, 'Northamptonshire', 908, 0],
 [25, 23, 'Lydia John', 4765, 'Wales', 884, 0],
 [22, 24, 'Lois Perryman', 281, 'Middlesex', 883, 0],
 [24, 25, 'Raquel São Pedro', 186977, 'Lincolnshire', 874, 0],
 [26, 26, 'Sandy Choong', 191450, 'Lancashire', 861, 1],
 [28, 27, 'Erin Green', 156732, 'Nottinghamshire', 852, 0],
 [27, 28, 'Sophie Barlow', 9039, 'ClevelandTTA', 851, 2],
 [30, 29, 'Grace Clement', 176566, 'Wales', 828, 0],
 [31, 30, 'Charlotte Weatherby', 2137, 'Durham', 826, 0],
 [0, 31, 'Lauren Stacey', 168508, 'Wales', 814, 0],
 [29, 32, 'Gracie Edwards', 3426, 'Essex', 799, 0],
 [36, 33, 'Amy Marriott', 172447, 'SouthYorkshire', 789, 0],
 [41, 34, 'Emily Haskell', 7718, 'Devonshire', 779, 0],
 [35, 35, 'Kirsty Maull', 170245, 'Staffordshire', 773, 0],
 [32, 36, 'Lucy Craig', 170952, 'Northen Ireland', 769, 0],
 [33, 37, 'Federica Bonato', 8007, 'Surrey', 759, 0],
 [37, 38, 'Jamie-Lee Harley', 95252, 'Wales', 754, 0],
 [45, 39, "Scarlett O'Neil", 159169, 'Kent', 753, 0],
 [34, 40, 'Helena Dicken', 165503, 'Derbyshire', 739, 0],
 [38, 41, 'Charlotte Marsden', 164036, 'Hertfordshire', 722, 2],
 [39, 42, 'Alice Dillon', 5036, 'Lancashire', 719, 1],
 [43, 43, 'Rana Rassem', 178568, 'Durham', 717, 0],
 [42, 44, 'Nicole Scott', 3589, 'Northen Ireland', 710, 0],
 [40, 45, 'Anais O`connor', 163985, 'Cheshire', 709, 0],
 [44, 46, 'Chloe Lingard', 90443, 'Lincolnshire', 689, 2],
 [46, 47, 'Alice Hazell', 2491, 'Sussex', 683, 0],
 [47, 48, 'Casey Nickle', 175867, 'Middlesex', 670, 1],
 [49, 49, 'Amillia Baker', 170138, 'Staffordshire', 668, 0],
 [48, 50, 'Scarlett Anders', 182173, 'Middlesex', 662, 2],
 [50, 51, 'Samadhi Udamulla', 168711, 'Hertfordshire', 634, 0],
 [51, 52, 'Sophie Newton', 165255, 'Lancashire', 633, 0],
 [56, 53, 'Megan Jones', 178314, 'Shropshire', 632, 0],
 [53, 54, 'Jodie Morris', 180375, 'Sussex', 626, 1],
 [52, 55, 'Angharad Beman', 168018, 'Devonshire', 625, 0],
 [54, 56, 'Medha Verma', 4145, 'Surrey', 617, 0],
 [55, 57, 'Morgan Davies', 184083, 'Wales', 612, 0],
 [70, 58, 'Anna Green', 156731, 'Nottinghamshire', 588, 0],
 [64, 59, 'Lauren Loosemore', 182770, 'Devonshire', 572, 0],
 [62, 60, 'Temeesha Hobbs', 158614, 'IsleOfWightTTA', 559, 0],
 [57, 61, 'Anya Milne', 175569, 'Durham', 557, 0],
 [58, 62, 'Pelin Karabulut', 178343, 'Oxfordshire', 557, 0],
 [59, 63, 'Jemma Walker', 217, 'Buckinghamshire', 546, 4],
 [60, 64, 'Aimee Evans', 2482, 'Staffordshire', 541, 1],
 [61, 65, 'Niamh Scarborough', 184178, 'Cheshire', 538, 0],
 [66, 66, 'Ella Barnard', 175316, 'Norfolk', 529, 0],
 [63, 67, 'Nicole Larmour', 196407, 'Northen Ireland', 525, 2],
 [67, 68, 'Sophie Rinnhofer', 154440, 'Warwickshire', 524, 0],
 [65, 69, 'Rebecca Savage', 177006, 'Durham', 519, 0],
 [68, 70, 'Nikka Zareh', 188155, 'Middlesex', 471, 2],
 [69, 71, 'Lucy McIvor', 200732, 'Northen Ireland', 470, 2],
 [94, 72, 'Stefania Popa', 173604, 'Lincolnshire', 464, 0],
 [72, 73, 'Wiktoria Smolarek', 180185, 'Scotland', 451, 0],
 [73, 74, 'Amy Mold', 184709, 'Durham', 446, 2],
 [74, 75, 'Pravesha Ragi', 197346, 'Ireland', 441, 1],
 [71, 76, 'Lucy Vernon', 174988, 'Derbyshire', 438, 0],
 [95, 77, 'Yuvathi Vijay', 178608, 'India', 433, 0],
 [79, 78, 'Natasha Johnston', 7282, 'Nottinghamshire', 422, 0],
 [76, 79, 'Joelle Bennett', 235, 'Sussex', 410, 0],
 [[77, 80, 'Emily Beasley', 162742, 'Warwickshire', 409, 1],
  [81, 81, 'Jyothirmayi Vaishnavi Ghanta', 191086, 'Berkshire', 407, 0]],
 [78, 82, 'Shristi Ghosh', 3093, 'Buckinghamshire', 399, 0],
 [75, 83, 'Bethan Jones', 190888, 'Wales', 399, 0],
 [80, 84, 'Aakanksha Tripathi', 153262, 'Lancashire', 397, 1],
 [82, 85, 'Bethany Brewer', 95253, 'Wales', 384, 2],
 [83, 86, 'Victoria Coll', 1183, 'Oxfordshire', 375, 1],
 [84, 87, 'Konstantina Apostologianni', 186298, 'Lancashire', 374, 2],
 [86, 88, 'Katie Bates', 178432, 'ClevelandTTA', 373, 0],
 [88, 89, 'Isabelle Lacorte', 182285, 'Hertfordshire', 369, 1],
 [85, 90, 'Isobella Khan', 172697, 'Avon', 364, 0],
 [102, 91, 'Abbie Hurley', 180556, 'Kent', 363, 0],
 [87, 92, 'Catherine Balshaw', 176142, 'Yorkshire', 361, 0],
 [90, 93, 'Lola McGhee', 176099, 'ClevelandTTA', 358, 2],
 [89, 94, 'Paula Callaghan', 193633, 'Scotland', 358, 0],
 [91, 95, 'Alexandra Robinson', 7663, 'Lincolnshire', 357, 2],
 [92, 96, 'Aimey Gerald', 169021, 'Middlesex', 351, 2],
 [99, 97, 'Anna Maria Besarabova', 170467, 'Bulgaria', 351, 0],
 [93, 98, 'Milly Green', 162815, 'Warwickshire', 349, 2],
 [96, 99, 'Katie Christoforou', 186657, 'Lincolnshire', 346, 4],
 [97, 100, 'Eve Witterick', 166744, 'ClevelandTTA', 343, 0],
 [98, 101, 'Maliha Baig', 182658, 'Essex', 341, 1],
 [100, 102, 'Sophie Barcsai', 183502, 'Dorset', 334, 1],
 [101, 103, 'Anna Kelly', 200733, 'Northen Ireland', 332, 2],
 [103, 104, 'Zoe Bennett', 157474, 'Devonshire', 319, 0],
 [104, 105, 'Rebecca Rigg', 173418, 'Cumbria-TableTennisEngland', 312, 0],
 [105, 106, 'Lok Yee (jade) Ngan', 193266, 'China', 308, 1],
 [106, 107, 'Jasmin Coker', 193961, 'Derbyshire', 302, 0],
 [108, 108, 'Talia Banin-Reid', 2904, 'Middlesex', 294, 4],
 [109, 109, 'Evelyn Pace', 198287, 'Surrey', 290, 0],
 [107, 110, 'Lucy Curtis', 165026, 'Suffolk', 283, 0],
 [116, 111, 'Sarah Amin', 176784, 'Yorkshire', 283, 0],
 [110, 112, 'Chloe Pryke', 164286, 'Cambridgeshire', 281, 1],
 [114, 113, 'Isobel McGerty', 170470, 'Suffolk', 281, 0],
 [111, 114, 'Nicola Dawson', 162995, 'Kent', 272, 2],
 [115, 115, 'Riya Kumar', 151795, 'Suffolk', 269, 1],
 [112, 116, 'Min Jie Guo', 54343, 'Kent', 261, 0],
 [113, 117, 'Mukmanee Warburton', 168175, 'Yorkshire', 261, 1],
 [117, 118, 'Isabel Webb', 59299, 'Kent', 256, 0],
 [118, 119, 'Ruby Bennett', 182233, 'Cheshire', 233, 2],
 [119, 120, 'Ebony Hempsell', 194373, 'Yorkshire', 222, 1],
 [120, 121, 'Reem Rassem', 180472, 'Durham', 212, 0],
 [121, 122, 'Edith Dedman', 177938, 'Dorset', 210, 3],
 [122, 123, 'Ciara Hancox', 164804, 'Warwickshire', 208, 2],
 [133, 124, 'Connie Dumelow', 190110, 'Derbyshire', 201, 0],
 [134, 125, 'Anna Piercey', 190241, 'Buckinghamshire', 200, 0],
 [124, 126, 'Darcy Brewer', 177360, 'Norfolk', 196, 0],
 [125, 127, 'Nina Oliva', 189966, 'Kent', 196, 3],
 [126, 128, 'Anna Wilson', 166137, 'Northamptonshire', 193, 2],
 [130, 129, 'Kate Watkinson', 184531, 'Lancashire', 193, 0],
 [127, 130, "Sasha O'Halloran", 184193, 'Sussex', 192, 0],
 [123, 131, 'Bethany Wootton', 163506, 'Staffordshire', 184, 0],
 [132, 132, 'Ellesse Trangmar', 187934, '-', 183, 4],
 [129, 133, 'Emily Ravetto', 186960, '-', 182, 2],
 [141, 134, 'Rachael Iles', 196802, 'Buckinghamshire', 178, 0],
 [153, 135, 'Eleanor Fletcher', 174251, 'Warwickshire', 175, 0],
 [135, 136, 'Abigail Ingles', 173605, 'Worcestershire', 172, 4],
 [136, 137, 'Ella Stanton', 186003, 'Dorset', 170, 0],
 [128, 138, 'Karishma Shah', 179769, 'Surrey', 169, 2],
 [138, 139, 'Saskia Key', 175113, 'Kent', 167, 0],
 [146, 140, 'Inderjeet Pawar', 191091, '-', 167, 0],
 [139, 141, 'Constance Reynolds', 187312, 'Hertfordshire', 165, 0],
 [145, 142, 'Heidi Oestreicher', 191095, 'Bedfordshire', 164, 0],
 [140, 143, 'Sienna Jetha', 189584, 'Middlesex', 161, 0],
 [0, 144, 'Naziyah Hasan', 200915, 'Surrey', 157, 0],
 [147, 145, 'Lucy Needham', 180481, 'Suffolk', 146, 0],
 [0, 146, 'Millie Flannagan', 187976, 'Middlesex', 145, 2],
 [143, 147, 'Rosa McKechnie', 177936, 'Dorset', 143, 2],
 [151, 148, 'Emily Koester', 190228, '-', 141, 0],
 [142, 149, 'Jessica Moggeridge', 182117, 'Dorset', 139, 0],
 [144, 150, 'Georgia Barker', 184025, 'Hampshire', 136, 3],
 [148, 151, 'Mia Charles', 186189, '-', 135, 0],
 [149, 152, 'Amalia Stern', 188212, 'Wiltshire', 122, 2],
 [150, 153, 'Shaniely Edwards', 191936, 'Bedfordshire', 118, 0],
 [161, 154, 'Libby Hudson', 185758, 'Kent', 117, 0],
 [156, 155, 'Natasha Richardson', 184303, '-', 115, 0],
 [152, 156, 'Chloe Kay', 180047, 'Devonshire', 110, 1],
 [154, 157, 'Anna Cole', 183288, 'Worcestershire', 107, 0],
 [155, 158, 'Sophie Arrandale', 188478, '-', 101, 0],
 [158, 159, 'Milly Hanrahan', 189394, 'Cheshire', 92, 0],
 [166, 160, 'Edie Huckel', 189177, '-', 91, 0],
 [159, 161, 'Bethany Ellis', 176155, 'Lancashire', 88, 0],
 [[157, 162, 'Holly Davis', 179712, 'Cornwall', 87, 0],
  [160, 163, 'Claudia Hough', 180634, '-', 79, 1]],
 [162, 164, 'Hannah Silcock', 197105, 'Jersey', 64, 0],
 [163, 165, 'Gypsie Kay', 180048, 'Devonshire', 63, 1],
 [164, 166, 'Lilli Foreman', 192073, 'Oxfordshire', 63, 0],
 [165, 167, 'Olivia Jones', 90514, 'Essex', 55, 1],
 [167, 168, 'Holly Calton', 192251, 'Dorset', 34, 0],
 [168, 169, 'Jodie Robertson', 189866, '-', 14, 1],
 [169, 170, 'Lucie Smith', 167203, 'SouthYorkshire', 13, 2]]

In [647]:
LLforXLS2=[]
for i in LLforXLS:
    if(len(i)==2):
        LLforXLS2.append(i[0])
        LLforXLS2.append(i[-1])
    else:
        LLforXLS2.append(i)

In [648]:
LLforXLS2

[[2, 1, 'Charlotte Bardsley', 163059, 'Staffordshire', 1488, 0],
 [1, 2, 'Denise Payet', 1344, 'Middlesex', 1474, 1],
 [3, 3, 'Jasmin Wong', 165375, 'Yorkshire', 1300, 0],
 [4, 4, 'Mollie Patterson', 446, 'Norfolk', 1257, 0],
 [5, 5, 'Darcie Proud', 90566, 'Lincolnshire', 1188, 0],
 [6, 6, 'Anna Hursey', 6482, 'Wales', 1175, 0],
 [7, 7, 'Annie Hedlund', 198701, 'Sweden', 1171, 2],
 [8, 8, 'Megan Gidney', 172935, 'Lancashire', 1158, 0],
 [10, 9, 'Beth Richards', 170063, 'Wales', 1106, 0],
 [9, 10, 'Gauri Duhan', 5655, 'Yorkshire', 1070, 0],
 [16, 11, 'Danielle Kelly', 80573, 'Wales', 1053, 0],
 [12, 12, 'Ruby Chan', 157565, 'Yorkshire', 1033, 0],
 [14, 13, 'Natalia Ianau', 167173, 'Middlesex', 1012, 0],
 [20, 14, 'Mari Baldwin', 175928, 'Devonshire', 1012, 0],
 [11, 15, 'Tiana Dennison', 3289, 'Essex', 1011, 0],
 [13, 16, 'Gemma Kerr', 165956, 'Devonshire', 992, 0],
 [15, 17, 'Anaya Patel', 172772, 'Berkshire', 991, 0],
 [21, 18, 'Lara Whitton', 166275, 'Wales', 983, 0],
 [19, 19, 'Katie Holt', 3128, 'Dorset', 980, 0],
 [17, 20, 'Nomin Baasan', 192519, 'Sweden', 972, 2],
 [18, 21, 'Millie Rogove', 180435, 'Hertfordshire', 970, 0],
 [23, 22, 'Bhavika Mistry', 8564, 'Northamptonshire', 908, 0],
 [25, 23, 'Lydia John', 4765, 'Wales', 884, 0],
 [22, 24, 'Lois Perryman', 281, 'Middlesex', 883, 0],
 [24, 25, 'Raquel São Pedro', 186977, 'Lincolnshire', 874, 0],
 [26, 26, 'Sandy Choong', 191450, 'Lancashire', 861, 1],
 [28, 27, 'Erin Green', 156732, 'Nottinghamshire', 852, 0],
 [27, 28, 'Sophie Barlow', 9039, 'ClevelandTTA', 851, 2],
 [30, 29, 'Grace Clement', 176566, 'Wales', 828, 0],
 [31, 30, 'Charlotte Weatherby', 2137, 'Durham', 826, 0],
 [0, 31, 'Lauren Stacey', 168508, 'Wales', 814, 0],
 [29, 32, 'Gracie Edwards', 3426, 'Essex', 799, 0],
 [36, 33, 'Amy Marriott', 172447, 'SouthYorkshire', 789, 0],
 [41, 34, 'Emily Haskell', 7718, 'Devonshire', 779, 0],
 [35, 35, 'Kirsty Maull', 170245, 'Staffordshire', 773, 0],
 [32, 36, 'Lucy Craig', 170952, 'Northen Ireland', 769, 0],
 [33, 37, 'Federica Bonato', 8007, 'Surrey', 759, 0],
 [37, 38, 'Jamie-Lee Harley', 95252, 'Wales', 754, 0],
 [45, 39, "Scarlett O'Neil", 159169, 'Kent', 753, 0],
 [34, 40, 'Helena Dicken', 165503, 'Derbyshire', 739, 0],
 [38, 41, 'Charlotte Marsden', 164036, 'Hertfordshire', 722, 2],
 [39, 42, 'Alice Dillon', 5036, 'Lancashire', 719, 1],
 [43, 43, 'Rana Rassem', 178568, 'Durham', 717, 0],
 [42, 44, 'Nicole Scott', 3589, 'Northen Ireland', 710, 0],
 [40, 45, 'Anais O`connor', 163985, 'Cheshire', 709, 0],
 [44, 46, 'Chloe Lingard', 90443, 'Lincolnshire', 689, 2],
 [46, 47, 'Alice Hazell', 2491, 'Sussex', 683, 0],
 [47, 48, 'Casey Nickle', 175867, 'Middlesex', 670, 1],
 [49, 49, 'Amillia Baker', 170138, 'Staffordshire', 668, 0],
 [48, 50, 'Scarlett Anders', 182173, 'Middlesex', 662, 2],
 [50, 51, 'Samadhi Udamulla', 168711, 'Hertfordshire', 634, 0],
 [51, 52, 'Sophie Newton', 165255, 'Lancashire', 633, 0],
 [56, 53, 'Megan Jones', 178314, 'Shropshire', 632, 0],
 [53, 54, 'Jodie Morris', 180375, 'Sussex', 626, 1],
 [52, 55, 'Angharad Beman', 168018, 'Devonshire', 625, 0],
 [54, 56, 'Medha Verma', 4145, 'Surrey', 617, 0],
 [55, 57, 'Morgan Davies', 184083, 'Wales', 612, 0],
 [70, 58, 'Anna Green', 156731, 'Nottinghamshire', 588, 0],
 [64, 59, 'Lauren Loosemore', 182770, 'Devonshire', 572, 0],
 [62, 60, 'Temeesha Hobbs', 158614, 'IsleOfWightTTA', 559, 0],
 [57, 61, 'Anya Milne', 175569, 'Durham', 557, 0],
 [58, 62, 'Pelin Karabulut', 178343, 'Oxfordshire', 557, 0],
 [59, 63, 'Jemma Walker', 217, 'Buckinghamshire', 546, 4],
 [60, 64, 'Aimee Evans', 2482, 'Staffordshire', 541, 1],
 [61, 65, 'Niamh Scarborough', 184178, 'Cheshire', 538, 0],
 [66, 66, 'Ella Barnard', 175316, 'Norfolk', 529, 0],
 [63, 67, 'Nicole Larmour', 196407, 'Northen Ireland', 525, 2],
 [67, 68, 'Sophie Rinnhofer', 154440, 'Warwickshire', 524, 0],
 [65, 69, 'Rebecca Savage', 177006, 'Durham', 519, 0],
 [68, 70, 'Nikka Zareh', 188155, 'Middlesex', 471, 2],
 [69, 71, 'Lucy McIvor', 200732, 'Northen Ireland', 470, 2],
 [94, 72, 'Stefania Popa', 173604, 'Lincolnshire', 464, 0],
 [72, 73, 'Wiktoria Smolarek', 180185, 'Scotland', 451, 0],
 [73, 74, 'Amy Mold', 184709, 'Durham', 446, 2],
 [74, 75, 'Pravesha Ragi', 197346, 'Ireland', 441, 1],
 [71, 76, 'Lucy Vernon', 174988, 'Derbyshire', 438, 0],
 [95, 77, 'Yuvathi Vijay', 178608, 'India', 433, 0],
 [79, 78, 'Natasha Johnston', 7282, 'Nottinghamshire', 422, 0],
 [76, 79, 'Joelle Bennett', 235, 'Sussex', 410, 0],
 [77, 80, 'Emily Beasley', 162742, 'Warwickshire', 409, 1],
 [81, 81, 'Jyothirmayi Vaishnavi Ghanta', 191086, 'Berkshire', 407, 0],
 [78, 82, 'Shristi Ghosh', 3093, 'Buckinghamshire', 399, 0],
 [75, 83, 'Bethan Jones', 190888, 'Wales', 399, 0],
 [80, 84, 'Aakanksha Tripathi', 153262, 'Lancashire', 397, 1],
 [82, 85, 'Bethany Brewer', 95253, 'Wales', 384, 2],
 [83, 86, 'Victoria Coll', 1183, 'Oxfordshire', 375, 1],
 [84, 87, 'Konstantina Apostologianni', 186298, 'Lancashire', 374, 2],
 [86, 88, 'Katie Bates', 178432, 'ClevelandTTA', 373, 0],
 [88, 89, 'Isabelle Lacorte', 182285, 'Hertfordshire', 369, 1],
 [85, 90, 'Isobella Khan', 172697, 'Avon', 364, 0],
 [102, 91, 'Abbie Hurley', 180556, 'Kent', 363, 0],
 [87, 92, 'Catherine Balshaw', 176142, 'Yorkshire', 361, 0],
 [90, 93, 'Lola McGhee', 176099, 'ClevelandTTA', 358, 2],
 [89, 94, 'Paula Callaghan', 193633, 'Scotland', 358, 0],
 [91, 95, 'Alexandra Robinson', 7663, 'Lincolnshire', 357, 2],
 [92, 96, 'Aimey Gerald', 169021, 'Middlesex', 351, 2],
 [99, 97, 'Anna Maria Besarabova', 170467, 'Bulgaria', 351, 0],
 [93, 98, 'Milly Green', 162815, 'Warwickshire', 349, 2],
 [96, 99, 'Katie Christoforou', 186657, 'Lincolnshire', 346, 4],
 [97, 100, 'Eve Witterick', 166744, 'ClevelandTTA', 343, 0],
 [98, 101, 'Maliha Baig', 182658, 'Essex', 341, 1],
 [100, 102, 'Sophie Barcsai', 183502, 'Dorset', 334, 1],
 [101, 103, 'Anna Kelly', 200733, 'Northen Ireland', 332, 2],
 [103, 104, 'Zoe Bennett', 157474, 'Devonshire', 319, 0],
 [104, 105, 'Rebecca Rigg', 173418, 'Cumbria-TableTennisEngland', 312, 0],
 [105, 106, 'Lok Yee (jade) Ngan', 193266, 'China', 308, 1],
 [106, 107, 'Jasmin Coker', 193961, 'Derbyshire', 302, 0],
 [108, 108, 'Talia Banin-Reid', 2904, 'Middlesex', 294, 4],
 [109, 109, 'Evelyn Pace', 198287, 'Surrey', 290, 0],
 [107, 110, 'Lucy Curtis', 165026, 'Suffolk', 283, 0],
 [116, 111, 'Sarah Amin', 176784, 'Yorkshire', 283, 0],
 [110, 112, 'Chloe Pryke', 164286, 'Cambridgeshire', 281, 1],
 [114, 113, 'Isobel McGerty', 170470, 'Suffolk', 281, 0],
 [111, 114, 'Nicola Dawson', 162995, 'Kent', 272, 2],
 [115, 115, 'Riya Kumar', 151795, 'Suffolk', 269, 1],
 [112, 116, 'Min Jie Guo', 54343, 'Kent', 261, 0],
 [113, 117, 'Mukmanee Warburton', 168175, 'Yorkshire', 261, 1],
 [117, 118, 'Isabel Webb', 59299, 'Kent', 256, 0],
 [118, 119, 'Ruby Bennett', 182233, 'Cheshire', 233, 2],
 [119, 120, 'Ebony Hempsell', 194373, 'Yorkshire', 222, 1],
 [120, 121, 'Reem Rassem', 180472, 'Durham', 212, 0],
 [121, 122, 'Edith Dedman', 177938, 'Dorset', 210, 3],
 [122, 123, 'Ciara Hancox', 164804, 'Warwickshire', 208, 2],
 [133, 124, 'Connie Dumelow', 190110, 'Derbyshire', 201, 0],
 [134, 125, 'Anna Piercey', 190241, 'Buckinghamshire', 200, 0],
 [124, 126, 'Darcy Brewer', 177360, 'Norfolk', 196, 0],
 [125, 127, 'Nina Oliva', 189966, 'Kent', 196, 3],
 [126, 128, 'Anna Wilson', 166137, 'Northamptonshire', 193, 2],
 [130, 129, 'Kate Watkinson', 184531, 'Lancashire', 193, 0],
 [127, 130, "Sasha O'Halloran", 184193, 'Sussex', 192, 0],
 [123, 131, 'Bethany Wootton', 163506, 'Staffordshire', 184, 0],
 [132, 132, 'Ellesse Trangmar', 187934, '-', 183, 4],
 [129, 133, 'Emily Ravetto', 186960, '-', 182, 2],
 [141, 134, 'Rachael Iles', 196802, 'Buckinghamshire', 178, 0],
 [153, 135, 'Eleanor Fletcher', 174251, 'Warwickshire', 175, 0],
 [135, 136, 'Abigail Ingles', 173605, 'Worcestershire', 172, 4],
 [136, 137, 'Ella Stanton', 186003, 'Dorset', 170, 0],
 [128, 138, 'Karishma Shah', 179769, 'Surrey', 169, 2],
 [138, 139, 'Saskia Key', 175113, 'Kent', 167, 0],
 [146, 140, 'Inderjeet Pawar', 191091, '-', 167, 0],
 [139, 141, 'Constance Reynolds', 187312, 'Hertfordshire', 165, 0],
 [145, 142, 'Heidi Oestreicher', 191095, 'Bedfordshire', 164, 0],
 [140, 143, 'Sienna Jetha', 189584, 'Middlesex', 161, 0],
 [0, 144, 'Naziyah Hasan', 200915, 'Surrey', 157, 0],
 [147, 145, 'Lucy Needham', 180481, 'Suffolk', 146, 0],
 [0, 146, 'Millie Flannagan', 187976, 'Middlesex', 145, 2],
 [143, 147, 'Rosa McKechnie', 177936, 'Dorset', 143, 2],
 [151, 148, 'Emily Koester', 190228, '-', 141, 0],
 [142, 149, 'Jessica Moggeridge', 182117, 'Dorset', 139, 0],
 [144, 150, 'Georgia Barker', 184025, 'Hampshire', 136, 3],
 [148, 151, 'Mia Charles', 186189, '-', 135, 0],
 [149, 152, 'Amalia Stern', 188212, 'Wiltshire', 122, 2],
 [150, 153, 'Shaniely Edwards', 191936, 'Bedfordshire', 118, 0],
 [161, 154, 'Libby Hudson', 185758, 'Kent', 117, 0],
 [156, 155, 'Natasha Richardson', 184303, '-', 115, 0],
 [152, 156, 'Chloe Kay', 180047, 'Devonshire', 110, 1],
 [154, 157, 'Anna Cole', 183288, 'Worcestershire', 107, 0],
 [155, 158, 'Sophie Arrandale', 188478, '-', 101, 0],
 [158, 159, 'Milly Hanrahan', 189394, 'Cheshire', 92, 0],
 [166, 160, 'Edie Huckel', 189177, '-', 91, 0],
 [159, 161, 'Bethany Ellis', 176155, 'Lancashire', 88, 0],
 [157, 162, 'Holly Davis', 179712, 'Cornwall', 87, 0],
 [160, 163, 'Claudia Hough', 180634, '-', 79, 1],
 [162, 164, 'Hannah Silcock', 197105, 'Jersey', 64, 0],
 [163, 165, 'Gypsie Kay', 180048, 'Devonshire', 63, 1],
 [164, 166, 'Lilli Foreman', 192073, 'Oxfordshire', 63, 0],
 [165, 167, 'Olivia Jones', 90514, 'Essex', 55, 1],
 [167, 168, 'Holly Calton', 192251, 'Dorset', 34, 0],
 [168, 169, 'Jodie Robertson', 189866, '-', 14, 1],
 [169, 170, 'Lucie Smith', 167203, 'SouthYorkshire', 13, 2]]

In [649]:
import pandas as pd
DF = pd.DataFrame(LLforXLS2)

In [650]:
DF

       0    1                    2       3                 4     5  6
0      2    1   Charlotte Bardsley  163059     Staffordshire  1488  0
1      1    2         Denise Payet    1344         Middlesex  1474  1
2      3    3          Jasmin Wong  165375         Yorkshire  1300  0
3      4    4     Mollie Patterson     446           Norfolk  1257  0
4      5    5         Darcie Proud   90566      Lincolnshire  1188  0
5      6    6          Anna Hursey    6482             Wales  1175  0
6      7    7        Annie Hedlund  198701            Sweden  1171  2
7      8    8         Megan Gidney  172935        Lancashire  1158  0
8     10    9        Beth Richards  170063             Wales  1106  0
9      9   10          Gauri Duhan    5655         Yorkshire  1070  0
10    16   11       Danielle Kelly   80573             Wales  1053  0
11    12   12            Ruby Chan  157565         Yorkshire  1033  0
12    14   13        Natalia Ianau  167173         Middlesex  1012  0
13    20   14         Mari Baldwin  175928        Devonshire  1012  0
14    11   15       Tiana Dennison    3289             Essex  1011  0
15    13   16           Gemma Kerr  165956        Devonshire   992  0
16    15   17          Anaya Patel  172772         Berkshire   991  0
17    21   18         Lara Whitton  166275             Wales   983  0
18    19   19           Katie Holt    3128            Dorset   980  0
19    17   20         Nomin Baasan  192519            Sweden   972  2
20    18   21        Millie Rogove  180435     Hertfordshire   970  0
21    23   22       Bhavika Mistry    8564  Northamptonshire   908  0
22    25   23           Lydia John    4765             Wales   884  0
23    22   24        Lois Perryman     281         Middlesex   883  0
24    24   25     Raquel São Pedro  186977      Lincolnshire   874  0
25    26   26         Sandy Choong  191450        Lancashire   861  1
26    28   27           Erin Green  156732   Nottinghamshire   852  0
27    27   28        Sophie Barlow    9039      ClevelandTTA   851  2
28    30   29        Grace Clement  176566             Wales   828  0
29    31   30  Charlotte Weatherby    2137            Durham   826  0
..   ...  ...                  ...     ...               ...   ... ..
140  139  141   Constance Reynolds  187312     Hertfordshire   165  0
141  145  142    Heidi Oestreicher  191095      Bedfordshire   164  0
142  140  143         Sienna Jetha  189584         Middlesex   161  0
143    0  144        Naziyah Hasan  200915            Surrey   157  0
144  147  145         Lucy Needham  180481           Suffolk   146  0
145    0  146     Millie Flannagan  187976         Middlesex   145  2
146  143  147       Rosa McKechnie  177936            Dorset   143  2
147  151  148        Emily Koester  190228                 -   141  0
148  142  149   Jessica Moggeridge  182117            Dorset   139  0
149  144  150       Georgia Barker  184025         Hampshire   136  3
150  148  151          Mia Charles  186189                 -   135  0
151  149  152         Amalia Stern  188212         Wiltshire   122  2
152  150  153     Shaniely Edwards  191936      Bedfordshire   118  0
153  161  154         Libby Hudson  185758              Kent   117  0
154  156  155   Natasha Richardson  184303                 -   115  0
155  152  156            Chloe Kay  180047        Devonshire   110  1
156  154  157            Anna Cole  183288    Worcestershire   107  0
157  155  158     Sophie Arrandale  188478                 -   101  0
158  158  159       Milly Hanrahan  189394          Cheshire    92  0
159  166  160          Edie Huckel  189177                 -    91  0
160  159  161        Bethany Ellis  176155        Lancashire    88  0
161  157  162          Holly Davis  179712          Cornwall    87  0
162  160  163        Claudia Hough  180634                 -    79  1
163  162  164       Hannah Silcock  197105            Jersey    64  0
164  163  165           Gypsie Kay  180048        Devonshire    63  1
165  164  166        Lilli Foreman  192073       Oxfordshire    63  0
166  165  167         Olivia Jones   90514             Essex    55  1
167  167  168         Holly Calton  192251            Dorset    34  0
168  168  169      Jodie Robertson  189866                 -    14  1
169  169  170          Lucie Smith  167203    SouthYorkshire    13  2

[170 rows x 7 columns]

In [651]:
keys=['PreviousRank','CurrentRank','Name','PlayerID','Country/County','Points','InactivePerioud']

In [652]:
DF.columns = keys

In [653]:
DF

,PreviousRank,CurrentRank,Name,PlayerID,Country/County,Points,InactivePerioud
0,2,1,Charlotte Bardsley,163059,Staffordshire,1488,0
1,1,2,Denise Payet,1344,Middlesex,1474,1
2,3,3,Jasmin Wong,165375,Yorkshire,1300,0
3,4,4,Mollie Patterson,446,Norfolk,1257,0
4,5,5,Darcie Proud,90566,Lincolnshire,1188,0
5,6,6,Anna Hursey,6482,Wales,1175,0
6,7,7,Annie Hedlund,198701,Sweden,1171,2
7,8,8,Megan Gidney,172935,Lancashire,1158,0
8,10,9,Beth Richards,170063,Wales,1106,0
9,9,10,Gauri Duhan,5655,Yorkshire,1070,0
10,16,11,Danielle Kelly,80573,Wales,1053,0
11,12,12,Ruby Chan,157565,Yorkshire,1033,0
12,14,13,Natalia Ianau,167173,Middlesex,1012,0
13,20,14,Mari Baldwin,175928,Devonshire,1012,0
14,11,15,Tiana Dennison,3289,Essex,1011,0
15,13,16,Gemma Kerr,165956,Devonshire,992,0
16,15,17,Anaya Patel,172772,Berkshire,991,0
17,21,18,Lara Whitton,166275,Wales,983,0
18,19,19,Katie Holt,3128,Dorset,980,0
19,17,20,Nomin Baasan,192519,Sweden,972,2
20,18,21,Millie Rogove,180435,Hertfordshire,970,0
21,23,22,Bhavika Mistry,8564,Northamptonshire,908,0
22,25,23,Lydia John,4765,Wales,884,0
23,22,24,Lois Perryman,281,Middlesex,883,0
24,24,25,Raquel São Pedro,186977,Lincolnshire,874,0
25,26,26,Sandy Choong,191450,Lancashire,861,1
26,28,27,Erin Green,156732,Nottinghamshire,852,0
27,27,28,Sophie Barlow,9039,ClevelandTTA,851,2
28,30,29,Grace Clement,176566,Wales,828,0
29,31,30,Charlotte Weatherby,2137,Durham,826,0
...,...,...,...,...,...,...,...
140,139,141,Constance Reynolds,187312,Hertfordshire,165,0
141,145,142,Heidi Oestreicher,191095,Bedfordshire,164,0
142,140,143,Sienna Jetha,189584,Middlesex,161,0
143,0,144,Naziyah Hasan,200915,Surrey,157,0
144,147,145,Lucy Needham,180481,Suffolk,146,0
145,0,146,Millie Flannagan,187976,Middlesex,145,2
146,143,147,Rosa McKechnie,177936,Dorset,143,2
147,151,148,Emily Koester,190228,-,141,0
148,142,149,Jessica Moggeridge,182117,Dorset,139,0
149,144,150,Georgia Barker,184025,Hampshire,136,3
150,148,151,Mia Charles,186189,-,135,0
151,149,152,Amalia Stern,188212,Wiltshire,122,2
152,150,153,Shaniely Edwards,191936,Bedfordshire,118,0
153,161,154,Libby Hudson,185758,Kent,117,0
154,156,155,Natasha Richardson,184303,-,115,0
155,152,156,Chloe Kay,180047,Devonshire,110,1
156,154,157,Anna Cole,183288,Worcestershire,107,0
157,155,158,Sophie Arrandale,188478,-,101,0
158,158,159,Milly Hanrahan,189394,Cheshire,92,0
159,166,160,Edie Huckel,189177,-,91,0
160,159,161,Bethany Ellis,176155,Lancashire,88,0
161,157,162,Holly Davis,179712,Cornwall,87,0
162,160,163,Claudia Hough,180634,-,79,1
163,162,164,Hannah Silcock,197105,Jersey,64,0
164,163,165,Gypsie Kay,180048,Devonshire,63,1
165,164,166,Lilli Foreman,192073,Oxfordshire,63,0
166,165,167,Olivia Jones,90514,Essex,55,1
167,167,168,Holly Calton,192251,Dorset,34,0
168,168,169,Jodie Robertson,189866,-,14,1
169,169,170,Lucie Smith,167203,SouthYorkshire,13,2

In [654]:
DF.to_excel('NewJANJuniorGirl.xlsx')